### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Settings
  commentId: N:VRBuilder.Editor.Settings
  id: VRBuilder.Editor.Settings
  children:
  - VRBuilder.Editor.Settings.BuilderProjectSettings
  - VRBuilder.Editor.Settings.InteractionComponentSettings
  langs:
  - csharp
  - vb
  name: VRBuilder.Editor.Settings
  nameWithType: VRBuilder.Editor.Settings
  fullName: VRBuilder.Editor.Settings
  type: Namespace
  assemblies:
  - VRBuilder.Editor
references:
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings
  commentId: T:VRBuilder.Editor.Settings.BuilderProjectSettings
  parent: VRBuilder.Editor.Settings
  href: VRBuilder.Editor.Settings.BuilderProjectSettings.html
  name: BuilderProjectSettings
  nameWithType: BuilderProjectSettings
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings
- uid: VRBuilder.Editor.Settings.InteractionComponentSettings
  commentId: T:VRBuilder.Editor.Settings.InteractionComponentSettings
  href: VRBuilder.Editor.Settings.InteractionComponentSettings.html
  name: InteractionComponentSettings
  nameWithType: InteractionComponentSettings
  fullName: VRBuilder.Editor.Settings.InteractionComponentSettings
- uid: VRBuilder.Editor.Settings
  commentId: N:VRBuilder.Editor.Settings
  href: VRBuilder.html
  name: VRBuilder.Editor.Settings
  nameWithType: VRBuilder.Editor.Settings
  fullName: VRBuilder.Editor.Settings
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Settings
    name: Settings
    href: VRBuilder.Editor.Settings.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Settings
    name: Settings
    href: VRBuilder.Editor.Settings.html
