### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.Modes.IRule`1
  commentId: T:VRBuilder.Core.Configuration.Modes.IRule`1
  id: IRule`1
  parent: VRBuilder.Core.Configuration.Modes
  children:
  - VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy(`0)
  langs:
  - csharp
  - vb
  name: IRule<T>
  nameWithType: IRule<T>
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/Modes/IRule.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IRule
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/Modes/IRule.cs
    startLine: 9
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration.Modes
  summary: Very generic interface which allows to implement a rule similar to Linq.Where or SQL Filter.
  example: []
  syntax:
    content: public interface IRule<T>
    typeParameters:
    - id: T
    content.vb: Public Interface IRule(Of T)
  nameWithType.vb: IRule(Of T)
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T)
  name.vb: IRule(Of T)
- uid: VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy(`0)
  commentId: M:VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy(`0)
  id: IsQualifiedBy(`0)
  parent: VRBuilder.Core.Configuration.Modes.IRule`1
  langs:
  - csharp
  - vb
  name: IsQualifiedBy(T)
  nameWithType: IRule<T>.IsQualifiedBy(T)
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>.IsQualifiedBy(T)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/Modes/IRule.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsQualifiedBy
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/Modes/IRule.cs
    startLine: 15
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration.Modes
  summary: Checks a given <code class="paramref">value</code> and returns true if this value qualifies the rule.
  example: []
  syntax:
    content: bool IsQualifiedBy(T value)
    parameters:
    - id: value
      type: '{T}'
      description: The type which is checked.
    return:
      type: System.Boolean
    content.vb: Function IsQualifiedBy(value As T) As Boolean
  overload: VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy*
  nameWithType.vb: IRule(Of T).IsQualifiedBy(T)
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T).IsQualifiedBy(T)
references:
- uid: VRBuilder.Core.Configuration.Modes
  commentId: N:VRBuilder.Core.Configuration.Modes
  href: VRBuilder.html
  name: VRBuilder.Core.Configuration.Modes
  nameWithType: VRBuilder.Core.Configuration.Modes
  fullName: VRBuilder.Core.Configuration.Modes
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
  - name: .
  - uid: VRBuilder.Core.Configuration.Modes
    name: Modes
    href: VRBuilder.Core.Configuration.Modes.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
  - name: .
  - uid: VRBuilder.Core.Configuration.Modes
    name: Modes
    href: VRBuilder.Core.Configuration.Modes.html
- uid: VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy*
  commentId: Overload:VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy
  href: VRBuilder.Core.Configuration.Modes.IRule-1.html#VRBuilder_Core_Configuration_Modes_IRule_1_IsQualifiedBy__0_
  name: IsQualifiedBy
  nameWithType: IRule<T>.IsQualifiedBy
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>.IsQualifiedBy
  nameWithType.vb: IRule(Of T).IsQualifiedBy
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T).IsQualifiedBy
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
