### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Setup.ILayerConfigurator
  commentId: T:VRBuilder.Core.Setup.ILayerConfigurator
  id: ILayerConfigurator
  parent: VRBuilder.Core.Setup
  children:
  - VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  - VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  langs:
  - csharp
  - vb
  name: ILayerConfigurator
  nameWithType: ILayerConfigurator
  fullName: VRBuilder.Core.Setup.ILayerConfigurator
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Setup/ILayerConfigurator.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ILayerConfigurator
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Setup/ILayerConfigurator.cs
    startLine: 5
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Setup
  summary: Can configure layer masks on an interactor or interactable.
  example: []
  syntax:
    content: public interface ILayerConfigurator
    content.vb: Public Interface ILayerConfigurator
- uid: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  commentId: P:VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  id: LayerSet
  parent: VRBuilder.Core.Setup.ILayerConfigurator
  langs:
  - csharp
  - vb
  name: LayerSet
  nameWithType: ILayerConfigurator.LayerSet
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Setup/ILayerConfigurator.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: LayerSet
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Setup/ILayerConfigurator.cs
    startLine: 10
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Setup
  summary: The layer set to be used on this configurator.
  example: []
  syntax:
    content: LayerSet LayerSet { get; }
    parameters: []
    return:
      type: VRBuilder.Core.Setup.LayerSet
    content.vb: ReadOnly Property LayerSet As LayerSet
  overload: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet*
- uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  commentId: M:VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  id: ConfigureLayers(System.String,System.String)
  parent: VRBuilder.Core.Setup.ILayerConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureLayers(string, string)
  nameWithType: ILayerConfigurator.ConfigureLayers(string, string)
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(string, string)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Setup/ILayerConfigurator.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ConfigureLayers
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Setup/ILayerConfigurator.cs
    startLine: 15
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Setup
  summary: Set up the layer masks to the specified layer names.
  example: []
  syntax:
    content: void ConfigureLayers(string interactionLayerName, string raycastLayerName)
    parameters:
    - id: interactionLayerName
      type: System.String
    - id: raycastLayerName
      type: System.String
    content.vb: Sub ConfigureLayers(interactionLayerName As String, raycastLayerName As String)
  overload: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers*
  nameWithType.vb: ILayerConfigurator.ConfigureLayers(String, String)
  fullName.vb: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(String, String)
  name.vb: ConfigureLayers(String, String)
references:
- uid: VRBuilder.Core.Setup
  commentId: N:VRBuilder.Core.Setup
  href: VRBuilder.html
  name: VRBuilder.Core.Setup
  nameWithType: VRBuilder.Core.Setup
  fullName: VRBuilder.Core.Setup
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Setup
    name: Setup
    href: VRBuilder.Core.Setup.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Setup
    name: Setup
    href: VRBuilder.Core.Setup.html
- uid: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet*
  commentId: Overload:VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  href: VRBuilder.Core.Setup.ILayerConfigurator.html#VRBuilder_Core_Setup_ILayerConfigurator_LayerSet
  name: LayerSet
  nameWithType: ILayerConfigurator.LayerSet
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
- uid: VRBuilder.Core.Setup.LayerSet
  commentId: T:VRBuilder.Core.Setup.LayerSet
  parent: VRBuilder.Core.Setup
  href: VRBuilder.Core.Setup.LayerSet.html
  name: LayerSet
  nameWithType: LayerSet
  fullName: VRBuilder.Core.Setup.LayerSet
- uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers*
  commentId: Overload:VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers
  href: VRBuilder.Core.Setup.ILayerConfigurator.html#VRBuilder_Core_Setup_ILayerConfigurator_ConfigureLayers_System_String_System_String_
  name: ConfigureLayers
  nameWithType: ILayerConfigurator.ConfigureLayers
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
