### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Settings.InteractionComponentSettings
  commentId: T:VRBuilder.Editor.Settings.InteractionComponentSettings
  id: InteractionComponentSettings
  parent: VRBuilder.Editor.Settings
  children:
  - VRBuilder.Editor.Settings.InteractionComponentSettings.EnableXRInteractionComponent
  langs:
  - csharp
  - vb
  name: InteractionComponentSettings
  nameWithType: InteractionComponentSettings
  fullName: VRBuilder.Editor.Settings.InteractionComponentSettings
  type: Class
  source:
    remote:
      path: Source/Core/Editor/Settings/InteractionComponentSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InteractionComponentSettings
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Settings/InteractionComponentSettings.cs
    startLine: 8
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  summary: "\nSettings related to VR Builder&apos;s interaction component.\n"
  example: []
  syntax:
    content: 'public class InteractionComponentSettings : SettingsObject<InteractionComponentSettings>'
    content.vb: >-
      Public Class InteractionComponentSettings
          Inherits SettingsObject(Of InteractionComponentSettings)
  inheritance:
  - System.Object
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}
  inheritedMembers:
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}.Instance
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}.Save
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Editor.Settings.InteractionComponentSettings.EnableXRInteractionComponent
  commentId: F:VRBuilder.Editor.Settings.InteractionComponentSettings.EnableXRInteractionComponent
  id: EnableXRInteractionComponent
  parent: VRBuilder.Editor.Settings.InteractionComponentSettings
  langs:
  - csharp
  - vb
  name: EnableXRInteractionComponent
  nameWithType: InteractionComponentSettings.EnableXRInteractionComponent
  fullName: VRBuilder.Editor.Settings.InteractionComponentSettings.EnableXRInteractionComponent
  type: Field
  source:
    remote:
      path: Source/Core/Editor/Settings/InteractionComponentSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: EnableXRInteractionComponent
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Settings/InteractionComponentSettings.cs
    startLine: 13
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  syntax:
    content: public bool EnableXRInteractionComponent
    return:
      type: System.Boolean
    content.vb: Public EnableXRInteractionComponent As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VRBuilder.Editor.Settings
  commentId: N:VRBuilder.Editor.Settings
  name: VRBuilder.Editor.Settings
  nameWithType: VRBuilder.Editor.Settings
  fullName: VRBuilder.Editor.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}
  parent: VRBuilder.Core.Runtime.Utils
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  name: SettingsObject<InteractionComponentSettings>
  nameWithType: SettingsObject<InteractionComponentSettings>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Editor.Settings.InteractionComponentSettings>
  nameWithType.vb: SettingsObject(Of InteractionComponentSettings)
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Editor.Settings.InteractionComponentSettings)
  name.vb: SettingsObject(Of InteractionComponentSettings)
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: <
    nameWithType: <
    fullName: <
  - uid: VRBuilder.Editor.Settings.InteractionComponentSettings
    name: InteractionComponentSettings
    nameWithType: InteractionComponentSettings
    fullName: VRBuilder.Editor.Settings.InteractionComponentSettings
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: VRBuilder.Editor.Settings.InteractionComponentSettings
    name: InteractionComponentSettings
    nameWithType: InteractionComponentSettings
    fullName: VRBuilder.Editor.Settings.InteractionComponentSettings
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}.Instance
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<InteractionComponentSettings>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Editor.Settings.InteractionComponentSettings>.Instance
  nameWithType.vb: SettingsObject(Of InteractionComponentSettings).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Editor.Settings.InteractionComponentSettings).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}.Save
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Editor.Settings.InteractionComponentSettings}
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save()
  nameWithType: SettingsObject<InteractionComponentSettings>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Editor.Settings.InteractionComponentSettings>.Save()
  nameWithType.vb: SettingsObject(Of InteractionComponentSettings).Save()
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Editor.Settings.InteractionComponentSettings).Save()
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject<InteractionComponentSettings>.Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Editor.Settings.InteractionComponentSettings>.Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject(Of InteractionComponentSettings).Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Editor.Settings.InteractionComponentSettings).Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject`1
  name: SettingsObject<T>
  nameWithType: SettingsObject<T>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>
  nameWithType.vb: SettingsObject(Of T)
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T)
  name.vb: SettingsObject(Of T)
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Runtime.Utils
  commentId: N:VRBuilder.Core.Runtime.Utils
  name: VRBuilder.Core.Runtime.Utils
  nameWithType: VRBuilder.Core.Runtime.Utils
  fullName: VRBuilder.Core.Runtime.Utils
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<T>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Instance
  nameWithType.vb: SettingsObject(Of T).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save()
  nameWithType: SettingsObject<T>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save()
  nameWithType.vb: SettingsObject(Of T).Save()
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save()
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject<T>.Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject(Of T).Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
