### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Animations.Configuration
  commentId: N:VRBuilder.Editor.Animations.Configuration
  id: VRBuilder.Editor.Animations.Configuration
  children:
  - VRBuilder.Editor.Animations.Configuration.AnimationsConfigurationExtension
  langs:
  - csharp
  - vb
  name: VRBuilder.Editor.Animations.Configuration
  nameWithType: VRBuilder.Editor.Animations.Configuration
  fullName: VRBuilder.Editor.Animations.Configuration
  type: Namespace
  assemblies:
  - VRBuilder.Editor.Animations
references:
- uid: VRBuilder.Editor.Animations.Configuration.AnimationsConfigurationExtension
  commentId: T:VRBuilder.Editor.Animations.Configuration.AnimationsConfigurationExtension
  href: VRBuilder.Editor.Animations.Configuration.AnimationsConfigurationExtension.html
  name: AnimationsConfigurationExtension
  nameWithType: AnimationsConfigurationExtension
  fullName: VRBuilder.Editor.Animations.Configuration.AnimationsConfigurationExtension
