### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider
  commentId: T:VRBuilder.Editor.UI.LanguageSettingsProvider
  id: LanguageSettingsProvider
  parent: VRBuilder.Editor.UI
  children:
  - VRBuilder.Editor.UI.LanguageSettingsProvider.#ctor
  - VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw(System.String)
  - VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate
  - VRBuilder.Editor.UI.LanguageSettingsProvider.Provider
  langs:
  - csharp
  - vb
  name: LanguageSettingsProvider
  nameWithType: LanguageSettingsProvider
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider
  type: Class
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: LanguageSettingsProvider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
    startLine: 13
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: 'public class LanguageSettingsProvider : BaseSettingsProvider'
    content.vb: >-
      Public Class LanguageSettingsProvider
          Inherits BaseSettingsProvider
  inheritance:
  - System.Object
  - VRBuilder.Editor.UI.BaseSettingsProvider
  inheritedMembers:
  - VRBuilder.Editor.UI.BaseSettingsProvider.sections
  - VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.#ctor
  commentId: M:VRBuilder.Editor.UI.LanguageSettingsProvider.#ctor
  id: '#ctor'
  parent: VRBuilder.Editor.UI.LanguageSettingsProvider
  langs:
  - csharp
  - vb
  name: LanguageSettingsProvider()
  nameWithType: LanguageSettingsProvider.LanguageSettingsProvider()
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.LanguageSettingsProvider()
  type: Constructor
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
    startLine: 17
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: public LanguageSettingsProvider()
    content.vb: Public Sub New
  overload: VRBuilder.Editor.UI.LanguageSettingsProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw(System.String)
  commentId: M:VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw(System.String)
  id: InternalDraw(System.String)
  parent: VRBuilder.Editor.UI.LanguageSettingsProvider
  langs:
  - csharp
  - vb
  name: InternalDraw(String)
  nameWithType: LanguageSettingsProvider.InternalDraw(String)
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InternalDraw
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
    startLine: 19
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: protected override void InternalDraw(string searchContext)
    parameters:
    - id: searchContext
      type: System.String
    content.vb: Protected Overrides Sub InternalDraw(searchContext As String)
  overridden: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  overload: VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate
  commentId: M:VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate
  id: OnDeactivate
  parent: VRBuilder.Editor.UI.LanguageSettingsProvider
  langs:
  - csharp
  - vb
  name: OnDeactivate()
  nameWithType: LanguageSettingsProvider.OnDeactivate()
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnDeactivate
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
    startLine: 89
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: public override void OnDeactivate()
    content.vb: Public Overrides Sub OnDeactivate
  overload: VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.Provider
  commentId: M:VRBuilder.Editor.UI.LanguageSettingsProvider.Provider
  id: Provider
  parent: VRBuilder.Editor.UI.LanguageSettingsProvider
  langs:
  - csharp
  - vb
  name: Provider()
  nameWithType: LanguageSettingsProvider.Provider()
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.Provider()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Provider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/LanguageSettingsProvider.cs
    startLine: 97
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: public static SettingsProvider Provider()
    return:
      type: SettingsProvider
    content.vb: Public Shared Function Provider As SettingsProvider
  overload: VRBuilder.Editor.UI.LanguageSettingsProvider.Provider*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: VRBuilder.Editor.UI
  commentId: N:VRBuilder.Editor.UI
  name: VRBuilder.Editor.UI
  nameWithType: VRBuilder.Editor.UI
  fullName: VRBuilder.Editor.UI
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.Editor.UI.BaseSettingsProvider
  commentId: T:VRBuilder.Editor.UI.BaseSettingsProvider
  parent: VRBuilder.Editor.UI
  name: BaseSettingsProvider
  nameWithType: BaseSettingsProvider
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.sections
  commentId: F:VRBuilder.Editor.UI.BaseSettingsProvider.sections
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  name: sections
  nameWithType: BaseSettingsProvider.sections
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.sections
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  isExternal: true
  name: OnGUI(String)
  nameWithType: BaseSettingsProvider.OnGUI(String)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  spec.csharp:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
    name: OnGUI
    nameWithType: BaseSettingsProvider.OnGUI
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
    name: OnGUI
    nameWithType: BaseSettingsProvider.OnGUI
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.#ctor*
  commentId: Overload:VRBuilder.Editor.UI.LanguageSettingsProvider.#ctor
  name: LanguageSettingsProvider
  nameWithType: LanguageSettingsProvider.LanguageSettingsProvider
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.LanguageSettingsProvider
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  isExternal: true
  name: InternalDraw(String)
  nameWithType: BaseSettingsProvider.InternalDraw(String)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  spec.csharp:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
    name: InternalDraw
    nameWithType: BaseSettingsProvider.InternalDraw
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
    name: InternalDraw
    nameWithType: BaseSettingsProvider.InternalDraw
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw*
  commentId: Overload:VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw
  name: InternalDraw
  nameWithType: LanguageSettingsProvider.InternalDraw
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.InternalDraw
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate*
  commentId: Overload:VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate
  name: OnDeactivate
  nameWithType: LanguageSettingsProvider.OnDeactivate
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.OnDeactivate
- uid: VRBuilder.Editor.UI.LanguageSettingsProvider.Provider*
  commentId: Overload:VRBuilder.Editor.UI.LanguageSettingsProvider.Provider
  name: Provider
  nameWithType: LanguageSettingsProvider.Provider
  fullName: VRBuilder.Editor.UI.LanguageSettingsProvider.Provider
- uid: SettingsProvider
  isExternal: true
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: SettingsProvider
