### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.UI.IProjectSettingsSection
  commentId: T:VRBuilder.Editor.UI.IProjectSettingsSection
  id: IProjectSettingsSection
  parent: VRBuilder.Editor.UI
  children:
  - VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  - VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  - VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  - VRBuilder.Editor.UI.IProjectSettingsSection.Title
  langs:
  - csharp
  - vb
  name: IProjectSettingsSection
  nameWithType: IProjectSettingsSection
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection
  type: Interface
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IProjectSettingsSection
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 11
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: Allows to inject a settings section into a setting provider.
  example: []
  syntax:
    content: public interface IProjectSettingsSection
    content.vb: Public Interface IProjectSettingsSection
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Title
  commentId: P:VRBuilder.Editor.UI.IProjectSettingsSection.Title
  id: Title
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: Title
  nameWithType: IProjectSettingsSection.Title
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Title
  type: Property
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Title
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 16
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: Title of this section.
  example: []
  syntax:
    content: string Title { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Title As String
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.Title*
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  commentId: P:VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  id: TargetPageProvider
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: TargetPageProvider
  nameWithType: IProjectSettingsSection.TargetPageProvider
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  type: Property
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: TargetPageProvider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 21
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: Type of the target setting provider.
  example: []
  syntax:
    content: Type TargetPageProvider { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: ReadOnly Property TargetPageProvider As Type
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider*
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  commentId: P:VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  id: Priority
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: IProjectSettingsSection.Priority
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  type: Property
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Priority
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 26
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: Determines the draw order, lower priority will be drawn first.
  example: []
  syntax:
    content: int Priority { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property Priority As Integer
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.Priority*
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  commentId: M:VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  id: OnGUI(System.String)
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: OnGUI(string)
  nameWithType: IProjectSettingsSection.OnGUI(string)
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(string)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnGUI
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 31
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: Your draw call.
  example: []
  syntax:
    content: void OnGUI(string searchContext)
    parameters:
    - id: searchContext
      type: System.String
    content.vb: Sub OnGUI(searchContext As String)
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI*
  nameWithType.vb: IProjectSettingsSection.OnGUI(String)
  fullName.vb: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(String)
  name.vb: OnGUI(String)
references:
- uid: VRBuilder.Editor.UI
  commentId: N:VRBuilder.Editor.UI
  href: VRBuilder.html
  name: VRBuilder.Editor.UI
  nameWithType: VRBuilder.Editor.UI
  fullName: VRBuilder.Editor.UI
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.UI
    name: UI
    href: VRBuilder.Editor.UI.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.UI
    name: UI
    href: VRBuilder.Editor.UI.html
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Title*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.Title
  href: VRBuilder.Editor.UI.IProjectSettingsSection.html#VRBuilder_Editor_UI_IProjectSettingsSection_Title
  name: Title
  nameWithType: IProjectSettingsSection.Title
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Title
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  href: VRBuilder.Editor.UI.IProjectSettingsSection.html#VRBuilder_Editor_UI_IProjectSettingsSection_TargetPageProvider
  name: TargetPageProvider
  nameWithType: IProjectSettingsSection.TargetPageProvider
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.type
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Priority*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  href: VRBuilder.Editor.UI.IProjectSettingsSection.html#VRBuilder_Editor_UI_IProjectSettingsSection_Priority
  name: Priority
  nameWithType: IProjectSettingsSection.Priority
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Priority
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI
  href: VRBuilder.Editor.UI.IProjectSettingsSection.html#VRBuilder_Editor_UI_IProjectSettingsSection_OnGUI_System_String_
  name: OnGUI
  nameWithType: IProjectSettingsSection.OnGUI
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI
