### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Settings.InteractionSettings
  commentId: T:VRBuilder.Core.Settings.InteractionSettings
  id: InteractionSettings
  parent: VRBuilder.Core.Settings
  children:
  - VRBuilder.Core.Settings.InteractionSettings.MakeGrabbablesKinematic
  langs:
  - csharp
  - vb
  name: InteractionSettings
  nameWithType: InteractionSettings
  fullName: VRBuilder.Core.Settings.InteractionSettings
  type: Class
  source:
    remote:
      path: Source/Core/Runtime/Settings/InteractionSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InteractionSettings
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/InteractionSettings.cs
    startLine: 8
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  summary: "\nSettings related to VR Builder&apos;s default interaction behaviour.\n"
  example: []
  syntax:
    content: 'public class InteractionSettings : SettingsObject<InteractionSettings>'
    content.vb: >-
      Public Class InteractionSettings
          Inherits SettingsObject(Of InteractionSettings)
  inheritance:
  - System.Object
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}
  inheritedMembers:
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}.Instance
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}.Save
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Core.Settings.InteractionSettings.MakeGrabbablesKinematic
  commentId: F:VRBuilder.Core.Settings.InteractionSettings.MakeGrabbablesKinematic
  id: MakeGrabbablesKinematic
  parent: VRBuilder.Core.Settings.InteractionSettings
  langs:
  - csharp
  - vb
  name: MakeGrabbablesKinematic
  nameWithType: InteractionSettings.MakeGrabbablesKinematic
  fullName: VRBuilder.Core.Settings.InteractionSettings.MakeGrabbablesKinematic
  type: Field
  source:
    remote:
      path: Source/Core/Runtime/Settings/InteractionSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: MakeGrabbablesKinematic
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/InteractionSettings.cs
    startLine: 13
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public bool MakeGrabbablesKinematic
    return:
      type: System.Boolean
    content.vb: Public MakeGrabbablesKinematic As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VRBuilder.Core.Settings
  commentId: N:VRBuilder.Core.Settings
  name: VRBuilder.Core.Settings
  nameWithType: VRBuilder.Core.Settings
  fullName: VRBuilder.Core.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}
  parent: VRBuilder.Core.Runtime.Utils
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  name: SettingsObject<InteractionSettings>
  nameWithType: SettingsObject<InteractionSettings>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Settings.InteractionSettings>
  nameWithType.vb: SettingsObject(Of InteractionSettings)
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Settings.InteractionSettings)
  name.vb: SettingsObject(Of InteractionSettings)
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: <
    nameWithType: <
    fullName: <
  - uid: VRBuilder.Core.Settings.InteractionSettings
    name: InteractionSettings
    nameWithType: InteractionSettings
    fullName: VRBuilder.Core.Settings.InteractionSettings
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: VRBuilder.Core.Settings.InteractionSettings
    name: InteractionSettings
    nameWithType: InteractionSettings
    fullName: VRBuilder.Core.Settings.InteractionSettings
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}.Instance
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<InteractionSettings>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Settings.InteractionSettings>.Instance
  nameWithType.vb: SettingsObject(Of InteractionSettings).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Settings.InteractionSettings).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}.Save
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Settings.InteractionSettings}
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save()
  nameWithType: SettingsObject<InteractionSettings>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Settings.InteractionSettings>.Save()
  nameWithType.vb: SettingsObject(Of InteractionSettings).Save()
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Settings.InteractionSettings).Save()
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject<InteractionSettings>.Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Settings.InteractionSettings>.Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject(Of InteractionSettings).Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Settings.InteractionSettings).Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject`1
  name: SettingsObject<T>
  nameWithType: SettingsObject<T>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>
  nameWithType.vb: SettingsObject(Of T)
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T)
  name.vb: SettingsObject(Of T)
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Runtime.Utils
  commentId: N:VRBuilder.Core.Runtime.Utils
  name: VRBuilder.Core.Runtime.Utils
  nameWithType: VRBuilder.Core.Runtime.Utils
  fullName: VRBuilder.Core.Runtime.Utils
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<T>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Instance
  nameWithType.vb: SettingsObject(Of T).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save()
  nameWithType: SettingsObject<T>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save()
  nameWithType.vb: SettingsObject(Of T).Save()
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save()
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject<T>.Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject(Of T).Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
