### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.RestrictiveEnvironment
  commentId: N:VRBuilder.Core.RestrictiveEnvironment
  id: VRBuilder.Core.RestrictiveEnvironment
  children:
  - VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
  - VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
  - VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
  - VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
  langs:
  - csharp
  - vb
  name: VRBuilder.Core.RestrictiveEnvironment
  nameWithType: VRBuilder.Core.RestrictiveEnvironment
  fullName: VRBuilder.Core.RestrictiveEnvironment
  type: Namespace
  assemblies:
  - VRBuilder.Core
references:
- uid: VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
  name: DefaultStepLockHandling
  nameWithType: DefaultStepLockHandling
  fullName: VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
- uid: VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
  parent: VRBuilder.Core.RestrictiveEnvironment
  name: LockablePropertyData
  nameWithType: LockablePropertyData
  fullName: VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
- uid: VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
  parent: VRBuilder.Core.RestrictiveEnvironment
  name: StepLockHandlingStrategy
  nameWithType: StepLockHandlingStrategy
  fullName: VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
- uid: VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
  name: NonLockingStepHandling
  nameWithType: NonLockingStepHandling
  fullName: VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
- uid: VRBuilder.Core.RestrictiveEnvironment
  commentId: N:VRBuilder.Core.RestrictiveEnvironment
  name: VRBuilder.Core.RestrictiveEnvironment
  nameWithType: VRBuilder.Core.RestrictiveEnvironment
  fullName: VRBuilder.Core.RestrictiveEnvironment
