### YamlMime:ManagedReference
items:
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  commentId: T:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  id: RuntimeConfigurationExtensions
  parent: VRBuilder.TextToSpeech
  children:
  - VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  - VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  langs:
  - csharp
  - vb
  name: RuntimeConfigurationExtensions
  nameWithType: RuntimeConfigurationExtensions
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  type: Class
  source:
    remote:
      path: Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RuntimeConfigurationExtensions
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
    startLine: 7
  assemblies:
  - VRBuilder.TextToSpeech
  namespace: VRBuilder.TextToSpeech
  summary: TextToSpeech extensions methods for <xref href="VRBuilder.Core.Configuration.BaseRuntimeConfiguration" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static class RuntimeConfigurationExtensions
    content.vb: Public Module RuntimeConfigurationExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  commentId: M:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  id: GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  isExtensionMethod: true
  parent: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  langs:
  - csharp
  - vb
  name: GetTextToSpeechConfiguration(BaseRuntimeConfiguration)
  nameWithType: RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(BaseRuntimeConfiguration)
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  type: Method
  source:
    remote:
      path: Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: GetTextToSpeechConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
    startLine: 17
  assemblies:
  - VRBuilder.TextToSpeech
  namespace: VRBuilder.TextToSpeech
  summary: Return loaded <xref href="VRBuilder.TextToSpeech.TextToSpeechConfiguration" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static TextToSpeechConfiguration GetTextToSpeechConfiguration(this BaseRuntimeConfiguration runtimeConfiguration)
    parameters:
    - id: runtimeConfiguration
      type: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
    return:
      type: VRBuilder.TextToSpeech.TextToSpeechConfiguration
    content.vb: Public Shared Function GetTextToSpeechConfiguration(runtimeConfiguration As BaseRuntimeConfiguration) As TextToSpeechConfiguration
  overload: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration*
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  commentId: M:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  id: SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  isExtensionMethod: true
  parent: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  langs:
  - csharp
  - vb
  name: SetTextToSpeechConfiguration(BaseRuntimeConfiguration, TextToSpeechConfiguration)
  nameWithType: RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(BaseRuntimeConfiguration, TextToSpeechConfiguration)
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration, VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  type: Method
  source:
    remote:
      path: Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SetTextToSpeechConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
    startLine: 30
  assemblies:
  - VRBuilder.TextToSpeech
  namespace: VRBuilder.TextToSpeech
  summary: Loads a new <xref href="VRBuilder.TextToSpeech.TextToSpeechConfiguration" data-throw-if-not-resolved="false"></xref>
  example: []
  syntax:
    content: public static void SetTextToSpeechConfiguration(this BaseRuntimeConfiguration runtimeConfiguration, TextToSpeechConfiguration ttsConfiguration)
    parameters:
    - id: runtimeConfiguration
      type: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
    - id: ttsConfiguration
      type: VRBuilder.TextToSpeech.TextToSpeechConfiguration
    content.vb: Public Shared Sub SetTextToSpeechConfiguration(runtimeConfiguration As BaseRuntimeConfiguration, ttsConfiguration As TextToSpeechConfiguration)
  overload: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration*
references:
- uid: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  commentId: T:VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  parent: VRBuilder.Core.Configuration
  href: VRBuilder.Core.Configuration.BaseRuntimeConfiguration.html
  name: BaseRuntimeConfiguration
  nameWithType: BaseRuntimeConfiguration
  fullName: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
- uid: VRBuilder.TextToSpeech
  commentId: N:VRBuilder.TextToSpeech
  href: VRBuilder.html
  name: VRBuilder.TextToSpeech
  nameWithType: VRBuilder.TextToSpeech
  fullName: VRBuilder.TextToSpeech
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.TextToSpeech
    name: TextToSpeech
    href: VRBuilder.TextToSpeech.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.TextToSpeech
    name: TextToSpeech
    href: VRBuilder.TextToSpeech.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  href: VRBuilder.html
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.TextToSpeech.TextToSpeechConfiguration
  commentId: T:VRBuilder.TextToSpeech.TextToSpeechConfiguration
  parent: VRBuilder.TextToSpeech
  href: VRBuilder.TextToSpeech.TextToSpeechConfiguration.html
  name: TextToSpeechConfiguration
  nameWithType: TextToSpeechConfiguration
  fullName: VRBuilder.TextToSpeech.TextToSpeechConfiguration
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration*
  commentId: Overload:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration
  href: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.html#VRBuilder_TextToSpeech_RuntimeConfigurationExtensions_GetTextToSpeechConfiguration_VRBuilder_Core_Configuration_BaseRuntimeConfiguration_
  name: GetTextToSpeechConfiguration
  nameWithType: RuntimeConfigurationExtensions.GetTextToSpeechConfiguration
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration*
  commentId: Overload:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration
  href: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.html#VRBuilder_TextToSpeech_RuntimeConfigurationExtensions_SetTextToSpeechConfiguration_VRBuilder_Core_Configuration_BaseRuntimeConfiguration_VRBuilder_TextToSpeech_TextToSpeechConfiguration_
  name: SetTextToSpeechConfiguration
  nameWithType: RuntimeConfigurationExtensions.SetTextToSpeechConfiguration
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration
