### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor
  commentId: T:VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor
  id: TextToSpeechConfigurationEditor
  parent: VRBuilder.Editor.TextToSpeech.UI
  children:
  - VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: TextToSpeechConfigurationEditor
  nameWithType: TextToSpeechConfigurationEditor
  fullName: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor
  type: Class
  source:
    remote:
      path: Source/TextToSpeech-Component/Editor/TextToSpeechConfigurationEditor.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: TextToSpeechConfigurationEditor
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Editor/TextToSpeechConfigurationEditor.cs
    startLine: 18
  assemblies:
  - VRBuilder.Editor.TextToSpeech
  namespace: VRBuilder.Editor.TextToSpeech.UI
  summary: "\nThis class draws list of <xref href=\"VRBuilder.TextToSpeech.ITextToSpeechProvider\" data-throw-if-not-resolved=\"false\"></xref> in <xref href=\"VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.textToSpeechConfiguration\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class TextToSpeechConfigurationEditor : Editor'
    content.vb: >-
      Public Class TextToSpeechConfigurationEditor
          Inherits Editor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI
  commentId: M:VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: TextToSpeechConfigurationEditor.OnInspectorGUI()
  fullName: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI()
  type: Method
  source:
    remote:
      path: Source/TextToSpeech-Component/Editor/TextToSpeechConfigurationEditor.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnInspectorGUI
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Editor/TextToSpeechConfigurationEditor.cs
    startLine: 35
  assemblies:
  - VRBuilder.Editor.TextToSpeech
  namespace: VRBuilder.Editor.TextToSpeech.UI
  example: []
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI
  overload: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: VRBuilder.TextToSpeech.ITextToSpeechProvider
  commentId: T:VRBuilder.TextToSpeech.ITextToSpeechProvider
  parent: VRBuilder.TextToSpeech
  name: ITextToSpeechProvider
  nameWithType: ITextToSpeechProvider
  fullName: VRBuilder.TextToSpeech.ITextToSpeechProvider
- uid: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.textToSpeechConfiguration
  commentId: F:VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.textToSpeechConfiguration
  isExternal: true
- uid: VRBuilder.Editor.TextToSpeech.UI
  commentId: N:VRBuilder.Editor.TextToSpeech.UI
  name: VRBuilder.Editor.TextToSpeech.UI
  nameWithType: VRBuilder.Editor.TextToSpeech.UI
  fullName: VRBuilder.Editor.TextToSpeech.UI
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.TextToSpeech
  commentId: N:VRBuilder.TextToSpeech
  name: VRBuilder.TextToSpeech
  nameWithType: VRBuilder.TextToSpeech
  fullName: VRBuilder.TextToSpeech
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI*
  commentId: Overload:VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: TextToSpeechConfigurationEditor.OnInspectorGUI
  fullName: VRBuilder.Editor.TextToSpeech.UI.TextToSpeechConfigurationEditor.OnInspectorGUI
