### YamlMime:ManagedReference
items:
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  commentId: T:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  id: RuntimeConfigurationExtensions
  parent: VRBuilder.TextToSpeech
  children:
  - VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  - VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  langs:
  - csharp
  - vb
  name: RuntimeConfigurationExtensions
  nameWithType: RuntimeConfigurationExtensions
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  type: Class
  source:
    remote:
      path: Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RuntimeConfigurationExtensions
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
    startLine: 7
  assemblies:
  - VRBuilder.TextToSpeech
  namespace: VRBuilder.TextToSpeech
  summary: "\nTextToSpeech extensions methods for <xref href=\"VRBuilder.Core.Configuration.BaseRuntimeConfiguration\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public static class RuntimeConfigurationExtensions
    content.vb: Public Module RuntimeConfigurationExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  commentId: M:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  id: GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  isExtensionMethod: true
  parent: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  langs:
  - csharp
  - vb
  name: GetTextToSpeechConfiguration(BaseRuntimeConfiguration)
  nameWithType: RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(BaseRuntimeConfiguration)
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration)
  type: Method
  source:
    remote:
      path: Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: GetTextToSpeechConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
    startLine: 17
  assemblies:
  - VRBuilder.TextToSpeech
  namespace: VRBuilder.TextToSpeech
  summary: "\nReturn loaded <xref href=\"VRBuilder.TextToSpeech.TextToSpeechConfiguration\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public static TextToSpeechConfiguration GetTextToSpeechConfiguration(this BaseRuntimeConfiguration runtimeConfiguration)
    parameters:
    - id: runtimeConfiguration
      type: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
    return:
      type: VRBuilder.TextToSpeech.TextToSpeechConfiguration
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function GetTextToSpeechConfiguration(runtimeConfiguration As BaseRuntimeConfiguration) As TextToSpeechConfiguration
  overload: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  commentId: M:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  id: SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration,VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  isExtensionMethod: true
  parent: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions
  langs:
  - csharp
  - vb
  name: SetTextToSpeechConfiguration(BaseRuntimeConfiguration, TextToSpeechConfiguration)
  nameWithType: RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(BaseRuntimeConfiguration, TextToSpeechConfiguration)
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration(VRBuilder.Core.Configuration.BaseRuntimeConfiguration, VRBuilder.TextToSpeech.TextToSpeechConfiguration)
  type: Method
  source:
    remote:
      path: Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SetTextToSpeechConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/TextToSpeech-Component/Runtime/RuntimeConfigurationExtensions.cs
    startLine: 30
  assemblies:
  - VRBuilder.TextToSpeech
  namespace: VRBuilder.TextToSpeech
  summary: "\nLoads a new <xref href=\"VRBuilder.TextToSpeech.TextToSpeechConfiguration\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: public static void SetTextToSpeechConfiguration(this BaseRuntimeConfiguration runtimeConfiguration, TextToSpeechConfiguration ttsConfiguration)
    parameters:
    - id: runtimeConfiguration
      type: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
    - id: ttsConfiguration
      type: VRBuilder.TextToSpeech.TextToSpeechConfiguration
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub SetTextToSpeechConfiguration(runtimeConfiguration As BaseRuntimeConfiguration, ttsConfiguration As TextToSpeechConfiguration)
  overload: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  commentId: T:VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  parent: VRBuilder.Core.Configuration
  name: BaseRuntimeConfiguration
  nameWithType: BaseRuntimeConfiguration
  fullName: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
- uid: VRBuilder.TextToSpeech
  commentId: N:VRBuilder.TextToSpeech
  name: VRBuilder.TextToSpeech
  nameWithType: VRBuilder.TextToSpeech
  fullName: VRBuilder.TextToSpeech
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.TextToSpeech.TextToSpeechConfiguration
  commentId: T:VRBuilder.TextToSpeech.TextToSpeechConfiguration
  parent: VRBuilder.TextToSpeech
  name: TextToSpeechConfiguration
  nameWithType: TextToSpeechConfiguration
  fullName: VRBuilder.TextToSpeech.TextToSpeechConfiguration
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration*
  commentId: Overload:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration
  name: GetTextToSpeechConfiguration
  nameWithType: RuntimeConfigurationExtensions.GetTextToSpeechConfiguration
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.GetTextToSpeechConfiguration
- uid: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration*
  commentId: Overload:VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration
  name: SetTextToSpeechConfiguration
  nameWithType: RuntimeConfigurationExtensions.SetTextToSpeechConfiguration
  fullName: VRBuilder.TextToSpeech.RuntimeConfigurationExtensions.SetTextToSpeechConfiguration
