### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  id: VRBuilder.Core.Configuration
  children:
  - VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  - VRBuilder.Core.Configuration.DefaultAudioPlayer
  - VRBuilder.Core.Configuration.DefaultRuntimeConfiguration
  - VRBuilder.Core.Configuration.DefaultSceneObjectManager
  - VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  - VRBuilder.Core.Configuration.IProcessAudioPlayer
  - VRBuilder.Core.Configuration.ISceneConfiguration
  - VRBuilder.Core.Configuration.ISceneObjectManager
  - VRBuilder.Core.Configuration.PropertyExtensionExclusionList
  - VRBuilder.Core.Configuration.RuntimeConfigurator
  - VRBuilder.Core.Configuration.SceneConfiguration
  langs:
  - csharp
  - vb
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
  type: Namespace
  assemblies:
  - VRBuilder.Core
references:
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  commentId: T:VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  parent: VRBuilder.Core.Configuration
  name: IInteractionComponentConfiguration
  nameWithType: IInteractionComponentConfiguration
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
- uid: VRBuilder.Core.Configuration.RuntimeConfigurator
  commentId: T:VRBuilder.Core.Configuration.RuntimeConfigurator
  parent: VRBuilder.Core.Configuration
  name: RuntimeConfigurator
  nameWithType: RuntimeConfigurator
  fullName: VRBuilder.Core.Configuration.RuntimeConfigurator
- uid: VRBuilder.Core.Configuration.DefaultAudioPlayer
  commentId: T:VRBuilder.Core.Configuration.DefaultAudioPlayer
  name: DefaultAudioPlayer
  nameWithType: DefaultAudioPlayer
  fullName: VRBuilder.Core.Configuration.DefaultAudioPlayer
- uid: VRBuilder.Core.Configuration.DefaultRuntimeConfiguration
  commentId: T:VRBuilder.Core.Configuration.DefaultRuntimeConfiguration
  name: DefaultRuntimeConfiguration
  nameWithType: DefaultRuntimeConfiguration
  fullName: VRBuilder.Core.Configuration.DefaultRuntimeConfiguration
- uid: VRBuilder.Core.Configuration.PropertyExtensionExclusionList
  commentId: T:VRBuilder.Core.Configuration.PropertyExtensionExclusionList
  name: PropertyExtensionExclusionList
  nameWithType: PropertyExtensionExclusionList
  fullName: VRBuilder.Core.Configuration.PropertyExtensionExclusionList
- uid: VRBuilder.Core.Configuration.ISceneObjectManager
  commentId: T:VRBuilder.Core.Configuration.ISceneObjectManager
  parent: VRBuilder.Core.Configuration
  name: ISceneObjectManager
  nameWithType: ISceneObjectManager
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer
  commentId: T:VRBuilder.Core.Configuration.IProcessAudioPlayer
  parent: VRBuilder.Core.Configuration
  name: IProcessAudioPlayer
  nameWithType: IProcessAudioPlayer
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer
- uid: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  commentId: T:VRBuilder.Core.Configuration.BaseRuntimeConfiguration
  parent: VRBuilder.Core.Configuration
  name: BaseRuntimeConfiguration
  nameWithType: BaseRuntimeConfiguration
  fullName: VRBuilder.Core.Configuration.BaseRuntimeConfiguration
- uid: VRBuilder.Core.Configuration.SceneConfiguration
  commentId: T:VRBuilder.Core.Configuration.SceneConfiguration
  name: SceneConfiguration
  nameWithType: SceneConfiguration
  fullName: VRBuilder.Core.Configuration.SceneConfiguration
- uid: VRBuilder.Core.Configuration.ISceneConfiguration
  commentId: T:VRBuilder.Core.Configuration.ISceneConfiguration
  parent: VRBuilder.Core.Configuration
  name: ISceneConfiguration
  nameWithType: ISceneConfiguration
  fullName: VRBuilder.Core.Configuration.ISceneConfiguration
- uid: VRBuilder.Core.Configuration.DefaultSceneObjectManager
  commentId: T:VRBuilder.Core.Configuration.DefaultSceneObjectManager
  name: DefaultSceneObjectManager
  nameWithType: DefaultSceneObjectManager
  fullName: VRBuilder.Core.Configuration.DefaultSceneObjectManager
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
