### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.ISceneObjectManager
  commentId: T:VRBuilder.Core.Configuration.ISceneObjectManager
  id: ISceneObjectManager
  parent: VRBuilder.Core.Configuration
  children:
  - VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab(UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion)
  - VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority(VRBuilder.Core.SceneObjects.ISceneObject)
  - VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive(VRBuilder.Core.SceneObjects.ISceneObject,System.String,System.Boolean)
  - VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive(VRBuilder.Core.SceneObjects.ISceneObject,System.Boolean)
  langs:
  - csharp
  - vb
  name: ISceneObjectManager
  nameWithType: ISceneObjectManager
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/ISceneObjectManager.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ISceneObjectManager
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/ISceneObjectManager.cs
    startLine: 8
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nObject that handles scene object operations, e.g. enabling/disabling them.\n"
  example: []
  syntax:
    content: public interface ISceneObjectManager
    content.vb: Public Interface ISceneObjectManager
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive(VRBuilder.Core.SceneObjects.ISceneObject,System.Boolean)
  commentId: M:VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive(VRBuilder.Core.SceneObjects.ISceneObject,System.Boolean)
  id: SetSceneObjectActive(VRBuilder.Core.SceneObjects.ISceneObject,System.Boolean)
  parent: VRBuilder.Core.Configuration.ISceneObjectManager
  langs:
  - csharp
  - vb
  name: SetSceneObjectActive(ISceneObject, Boolean)
  nameWithType: ISceneObjectManager.SetSceneObjectActive(ISceneObject, Boolean)
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive(VRBuilder.Core.SceneObjects.ISceneObject, System.Boolean)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/ISceneObjectManager.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SetSceneObjectActive
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/ISceneObjectManager.cs
    startLine: 13
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nSet the specified scene object enabled or disabled.\n"
  example: []
  syntax:
    content: void SetSceneObjectActive(ISceneObject sceneObject, bool isActive)
    parameters:
    - id: sceneObject
      type: VRBuilder.Core.SceneObjects.ISceneObject
    - id: isActive
      type: System.Boolean
    content.vb: Sub SetSceneObjectActive(sceneObject As ISceneObject, isActive As Boolean)
  overload: VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive*
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive(VRBuilder.Core.SceneObjects.ISceneObject,System.String,System.Boolean)
  commentId: M:VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive(VRBuilder.Core.SceneObjects.ISceneObject,System.String,System.Boolean)
  id: SetComponentActive(VRBuilder.Core.SceneObjects.ISceneObject,System.String,System.Boolean)
  parent: VRBuilder.Core.Configuration.ISceneObjectManager
  langs:
  - csharp
  - vb
  name: SetComponentActive(ISceneObject, String, Boolean)
  nameWithType: ISceneObjectManager.SetComponentActive(ISceneObject, String, Boolean)
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive(VRBuilder.Core.SceneObjects.ISceneObject, System.String, System.Boolean)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/ISceneObjectManager.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SetComponentActive
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/ISceneObjectManager.cs
    startLine: 18
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nSets all components of a given type on a specified scene object enabled or disabled.\n"
  example: []
  syntax:
    content: void SetComponentActive(ISceneObject sceneObject, string componentTypeName, bool isActive)
    parameters:
    - id: sceneObject
      type: VRBuilder.Core.SceneObjects.ISceneObject
    - id: componentTypeName
      type: System.String
    - id: isActive
      type: System.Boolean
    content.vb: Sub SetComponentActive(sceneObject As ISceneObject, componentTypeName As String, isActive As Boolean)
  overload: VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive*
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab(UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion)
  commentId: M:VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab(UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion)
  id: InstantiatePrefab(UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion)
  parent: VRBuilder.Core.Configuration.ISceneObjectManager
  langs:
  - csharp
  - vb
  name: InstantiatePrefab(GameObject, Vector3, Quaternion)
  nameWithType: ISceneObjectManager.InstantiatePrefab(GameObject, Vector3, Quaternion)
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab(UnityEngine.GameObject, UnityEngine.Vector3, UnityEngine.Quaternion)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/ISceneObjectManager.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InstantiatePrefab
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/ISceneObjectManager.cs
    startLine: 23
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nInstantiates the specified prefab.\n"
  example: []
  syntax:
    content: GameObject InstantiatePrefab(GameObject prefab, Vector3 position, Quaternion rotation)
    parameters:
    - id: prefab
      type: UnityEngine.GameObject
    - id: position
      type: UnityEngine.Vector3
    - id: rotation
      type: UnityEngine.Quaternion
    return:
      type: UnityEngine.GameObject
    content.vb: Function InstantiatePrefab(prefab As GameObject, position As Vector3, rotation As Quaternion) As GameObject
  overload: VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab*
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority(VRBuilder.Core.SceneObjects.ISceneObject)
  commentId: M:VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority(VRBuilder.Core.SceneObjects.ISceneObject)
  id: RequestAuthority(VRBuilder.Core.SceneObjects.ISceneObject)
  parent: VRBuilder.Core.Configuration.ISceneObjectManager
  langs:
  - csharp
  - vb
  name: RequestAuthority(ISceneObject)
  nameWithType: ISceneObjectManager.RequestAuthority(ISceneObject)
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority(VRBuilder.Core.SceneObjects.ISceneObject)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/ISceneObjectManager.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RequestAuthority
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/ISceneObjectManager.cs
    startLine: 28
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nRequests authority on the specified scene object.\n"
  example: []
  syntax:
    content: void RequestAuthority(ISceneObject sceneObject)
    parameters:
    - id: sceneObject
      type: VRBuilder.Core.SceneObjects.ISceneObject
    content.vb: Sub RequestAuthority(sceneObject As ISceneObject)
  overload: VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority*
references:
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive*
  commentId: Overload:VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive
  name: SetSceneObjectActive
  nameWithType: ISceneObjectManager.SetSceneObjectActive
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.SetSceneObjectActive
- uid: VRBuilder.Core.SceneObjects.ISceneObject
  commentId: T:VRBuilder.Core.SceneObjects.ISceneObject
  parent: VRBuilder.Core.SceneObjects
  name: ISceneObject
  nameWithType: ISceneObject
  fullName: VRBuilder.Core.SceneObjects.ISceneObject
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: VRBuilder.Core.SceneObjects
  commentId: N:VRBuilder.Core.SceneObjects
  name: VRBuilder.Core.SceneObjects
  nameWithType: VRBuilder.Core.SceneObjects
  fullName: VRBuilder.Core.SceneObjects
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive*
  commentId: Overload:VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive
  name: SetComponentActive
  nameWithType: ISceneObjectManager.SetComponentActive
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.SetComponentActive
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab*
  commentId: Overload:VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab
  name: InstantiatePrefab
  nameWithType: ISceneObjectManager.InstantiatePrefab
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.InstantiatePrefab
- uid: UnityEngine.GameObject
  commentId: T:UnityEngine.GameObject
  parent: UnityEngine
  isExternal: true
  name: GameObject
  nameWithType: GameObject
  fullName: UnityEngine.GameObject
- uid: UnityEngine.Vector3
  commentId: T:UnityEngine.Vector3
  parent: UnityEngine
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: UnityEngine.Vector3
- uid: UnityEngine.Quaternion
  commentId: T:UnityEngine.Quaternion
  parent: UnityEngine
  isExternal: true
  name: Quaternion
  nameWithType: Quaternion
  fullName: UnityEngine.Quaternion
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority*
  commentId: Overload:VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority
  name: RequestAuthority
  nameWithType: ISceneObjectManager.RequestAuthority
  fullName: VRBuilder.Core.Configuration.ISceneObjectManager.RequestAuthority
