### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.Modes.IConfigurator
  commentId: T:VRBuilder.Core.Configuration.Modes.IConfigurator
  id: IConfigurator
  parent: VRBuilder.Core.Configuration.Modes
  children:
  - VRBuilder.Core.Configuration.Modes.IConfigurator.Configure(VRBuilder.Core.Configuration.Modes.IMode,VRBuilder.Core.Stage)
  langs:
  - csharp
  - vb
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: VRBuilder.Core.Configuration.Modes.IConfigurator
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/Modes/IConfigurator.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IConfigurator
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/Modes/IConfigurator.cs
    startLine: 9
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration.Modes
  summary: "\nAn interface for entities&apos; configurators.\n"
  example: []
  syntax:
    content: public interface IConfigurator
    content.vb: Public Interface IConfigurator
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.Core.Configuration.Modes.IConfigurator.Configure(VRBuilder.Core.Configuration.Modes.IMode,VRBuilder.Core.Stage)
  commentId: M:VRBuilder.Core.Configuration.Modes.IConfigurator.Configure(VRBuilder.Core.Configuration.Modes.IMode,VRBuilder.Core.Stage)
  id: Configure(VRBuilder.Core.Configuration.Modes.IMode,VRBuilder.Core.Stage)
  parent: VRBuilder.Core.Configuration.Modes.IConfigurator
  langs:
  - csharp
  - vb
  name: Configure(IMode, Stage)
  nameWithType: IConfigurator.Configure(IMode, Stage)
  fullName: VRBuilder.Core.Configuration.Modes.IConfigurator.Configure(VRBuilder.Core.Configuration.Modes.IMode, VRBuilder.Core.Stage)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/Modes/IConfigurator.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Configure
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/Modes/IConfigurator.cs
    startLine: 13
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration.Modes
  syntax:
    content: void Configure(IMode mode, Stage stage)
    parameters:
    - id: mode
      type: VRBuilder.Core.Configuration.Modes.IMode
    - id: stage
      type: VRBuilder.Core.Stage
    content.vb: Sub Configure(mode As IMode, stage As Stage)
  overload: VRBuilder.Core.Configuration.Modes.IConfigurator.Configure*
references:
- uid: VRBuilder.Core.Configuration.Modes
  commentId: N:VRBuilder.Core.Configuration.Modes
  name: VRBuilder.Core.Configuration.Modes
  nameWithType: VRBuilder.Core.Configuration.Modes
  fullName: VRBuilder.Core.Configuration.Modes
- uid: VRBuilder.Core.Configuration.Modes.IConfigurator.Configure*
  commentId: Overload:VRBuilder.Core.Configuration.Modes.IConfigurator.Configure
  name: Configure
  nameWithType: IConfigurator.Configure
  fullName: VRBuilder.Core.Configuration.Modes.IConfigurator.Configure
- uid: VRBuilder.Core.Configuration.Modes.IMode
  commentId: T:VRBuilder.Core.Configuration.Modes.IMode
  parent: VRBuilder.Core.Configuration.Modes
  name: IMode
  nameWithType: IMode
  fullName: VRBuilder.Core.Configuration.Modes.IMode
- uid: VRBuilder.Core.Stage
  commentId: T:VRBuilder.Core.Stage
  parent: VRBuilder.Core
  name: Stage
  nameWithType: Stage
  fullName: VRBuilder.Core.Stage
- uid: VRBuilder.Core
  commentId: N:VRBuilder.Core
  name: VRBuilder.Core
  nameWithType: VRBuilder.Core
  fullName: VRBuilder.Core
