### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  id: VRBuilder.Editor.Configuration
  children:
  - VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
  - VRBuilder.Editor.Configuration.DefaultEditorConfiguration
  - VRBuilder.Editor.Configuration.EditorConfigurator
  - VRBuilder.Editor.Configuration.IEditorConfiguration
  - VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  - VRBuilder.Editor.Configuration.LoggingConfigCreationTrigger
  - VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  langs:
  - csharp
  - vb
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
  type: Namespace
  assemblies:
  - VRBuilder.Editor
references:
- uid: VRBuilder.Editor.Configuration.IEditorConfiguration
  commentId: T:VRBuilder.Editor.Configuration.IEditorConfiguration
  parent: VRBuilder.Editor.Configuration
  name: IEditorConfiguration
  nameWithType: IEditorConfiguration
  fullName: VRBuilder.Editor.Configuration.IEditorConfiguration
- uid: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
  commentId: T:VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
  parent: VRBuilder.Editor.Configuration
  name: AllowedMenuItemsSettings
  nameWithType: AllowedMenuItemsSettings
  fullName: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
- uid: VRBuilder.Editor.Configuration.LoggingConfigCreationTrigger
  commentId: T:VRBuilder.Editor.Configuration.LoggingConfigCreationTrigger
  name: LoggingConfigCreationTrigger
  nameWithType: LoggingConfigCreationTrigger
  fullName: VRBuilder.Editor.Configuration.LoggingConfigCreationTrigger
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  commentId: T:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  name: RuntimeConfiguratorEditor
  nameWithType: RuntimeConfiguratorEditor
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
- uid: VRBuilder.Editor.Configuration.DefaultEditorConfiguration
  commentId: T:VRBuilder.Editor.Configuration.DefaultEditorConfiguration
  parent: VRBuilder.Editor.Configuration
  name: DefaultEditorConfiguration
  nameWithType: DefaultEditorConfiguration
  fullName: VRBuilder.Editor.Configuration.DefaultEditorConfiguration
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  commentId: T:VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  parent: VRBuilder.Editor.Configuration
  name: IEditorConfigurationExtension
  nameWithType: IEditorConfigurationExtension
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
- uid: VRBuilder.Editor.Configuration.EditorConfigurator
  commentId: T:VRBuilder.Editor.Configuration.EditorConfigurator
  name: EditorConfigurator
  nameWithType: EditorConfigurator
  fullName: VRBuilder.Editor.Configuration.EditorConfigurator
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
