### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Setup.ILayerConfigurator
  commentId: T:VRBuilder.Core.Setup.ILayerConfigurator
  id: ILayerConfigurator
  parent: VRBuilder.Core.Setup
  children:
  - VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  - VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  langs:
  - csharp
  - vb
  name: ILayerConfigurator
  nameWithType: ILayerConfigurator
  fullName: VRBuilder.Core.Setup.ILayerConfigurator
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Setup/ILayerConfigurator.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ILayerConfigurator
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Setup/ILayerConfigurator.cs
    startLine: 5
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Setup
  summary: "\nCan configure layer masks on an interactor or interactable.\n"
  example: []
  syntax:
    content: public interface ILayerConfigurator
    content.vb: Public Interface ILayerConfigurator
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  commentId: P:VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  id: LayerSet
  parent: VRBuilder.Core.Setup.ILayerConfigurator
  langs:
  - csharp
  - vb
  name: LayerSet
  nameWithType: ILayerConfigurator.LayerSet
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Setup/ILayerConfigurator.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: LayerSet
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Setup/ILayerConfigurator.cs
    startLine: 10
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Setup
  summary: "\nThe layer set to be used on this configurator.\n"
  example: []
  syntax:
    content: LayerSet LayerSet { get; }
    parameters: []
    return:
      type: VRBuilder.Core.Setup.LayerSet
    content.vb: ReadOnly Property LayerSet As LayerSet
  overload: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  commentId: M:VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  id: ConfigureLayers(System.String,System.String)
  parent: VRBuilder.Core.Setup.ILayerConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureLayers(String, String)
  nameWithType: ILayerConfigurator.ConfigureLayers(String, String)
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String, System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Setup/ILayerConfigurator.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ConfigureLayers
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Setup/ILayerConfigurator.cs
    startLine: 15
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Setup
  summary: "\nSet up the layer masks to the specified layer names.\n"
  example: []
  syntax:
    content: void ConfigureLayers(string interactionLayerName, string raycastLayerName)
    parameters:
    - id: interactionLayerName
      type: System.String
    - id: raycastLayerName
      type: System.String
    content.vb: Sub ConfigureLayers(interactionLayerName As String, raycastLayerName As String)
  overload: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers*
references:
- uid: VRBuilder.Core.Setup
  commentId: N:VRBuilder.Core.Setup
  name: VRBuilder.Core.Setup
  nameWithType: VRBuilder.Core.Setup
  fullName: VRBuilder.Core.Setup
- uid: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet*
  commentId: Overload:VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  name: LayerSet
  nameWithType: ILayerConfigurator.LayerSet
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
- uid: VRBuilder.Core.Setup.LayerSet
  commentId: T:VRBuilder.Core.Setup.LayerSet
  parent: VRBuilder.Core.Setup
  name: LayerSet
  nameWithType: LayerSet
  fullName: VRBuilder.Core.Setup.LayerSet
- uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers*
  commentId: Overload:VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers
  name: ConfigureLayers
  nameWithType: ILayerConfigurator.ConfigureLayers
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
