### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer
  commentId: T:VRBuilder.Core.Configuration.IProcessAudioPlayer
  id: IProcessAudioPlayer
  parent: VRBuilder.Core.Configuration
  children:
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  langs:
  - csharp
  - vb
  name: IProcessAudioPlayer
  nameWithType: IProcessAudioPlayer
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IProcessAudioPlayer
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 8
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Interface for the class playing sounds for the process, i.e. tts and play audio behaviors.
  example: []
  syntax:
    content: public interface IProcessAudioPlayer
    content.vb: Public Interface IProcessAudioPlayer
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  commentId: P:VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  id: FallbackAudioSource
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: FallbackAudioSource
  nameWithType: IProcessAudioPlayer.FallbackAudioSource
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: FallbackAudioSource
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 13
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Gets a fallback audio source. Used only for backwards compatibility.
  example: []
  syntax:
    content: AudioSource FallbackAudioSource { get; }
    parameters: []
    return:
      type: UnityEngine.AudioSource
    content.vb: ReadOnly Property FallbackAudioSource As AudioSource
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource*
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  commentId: P:VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  id: IsPlaying
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: IsPlaying
  nameWithType: IProcessAudioPlayer.IsPlaying
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsPlaying
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 18
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: True if currently playing audio.
  example: []
  syntax:
    content: bool IsPlaying { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsPlaying As Boolean
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying*
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  commentId: M:VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  id: PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: PlayAudio(IAudioData, float, float)
  nameWithType: IProcessAudioPlayer.PlayAudio(IAudioData, float, float)
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData, float, float)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: PlayAudio
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 23
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Play the specified audio immediately with the set parameters.
  example: []
  syntax:
    content: void PlayAudio(IAudioData audioData, float volume = 1, float pitch = 1)
    parameters:
    - id: audioData
      type: VRBuilder.Core.Audio.IAudioData
    - id: volume
      type: System.Single
    - id: pitch
      type: System.Single
    content.vb: Sub PlayAudio(audioData As IAudioData, volume As Single = 1, pitch As Single = 1)
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio*
  nameWithType.vb: IProcessAudioPlayer.PlayAudio(IAudioData, Single, Single)
  fullName.vb: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData, Single, Single)
  name.vb: PlayAudio(IAudioData, Single, Single)
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  commentId: M:VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  id: Stop
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: Stop()
  nameWithType: IProcessAudioPlayer.Stop()
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop()
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Stop
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 28
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Stops playing audio.
  example: []
  syntax:
    content: void Stop()
    content.vb: Sub [Stop]()
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop*
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  commentId: M:VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  id: Reset
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: Reset()
  nameWithType: IProcessAudioPlayer.Reset()
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset()
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Reset
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 33
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Resets the player to its default settings.
  example: []
  syntax:
    content: void Reset()
    content.vb: Sub Reset()
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset*
references:
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  href: VRBuilder.html
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  href: VRBuilder.Core.Configuration.IProcessAudioPlayer.html#VRBuilder_Core_Configuration_IProcessAudioPlayer_FallbackAudioSource
  name: FallbackAudioSource
  nameWithType: IProcessAudioPlayer.FallbackAudioSource
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
- uid: UnityEngine.AudioSource
  commentId: T:UnityEngine.AudioSource
  parent: UnityEngine
  isExternal: true
  name: AudioSource
  nameWithType: AudioSource
  fullName: UnityEngine.AudioSource
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  href: VRBuilder.Core.Configuration.IProcessAudioPlayer.html#VRBuilder_Core_Configuration_IProcessAudioPlayer_IsPlaying
  name: IsPlaying
  nameWithType: IProcessAudioPlayer.IsPlaying
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio
  href: VRBuilder.Core.Configuration.IProcessAudioPlayer.html#VRBuilder_Core_Configuration_IProcessAudioPlayer_PlayAudio_VRBuilder_Core_Audio_IAudioData_System_Single_System_Single_
  name: PlayAudio
  nameWithType: IProcessAudioPlayer.PlayAudio
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio
- uid: VRBuilder.Core.Audio.IAudioData
  commentId: T:VRBuilder.Core.Audio.IAudioData
  parent: VRBuilder.Core.Audio
  href: VRBuilder.Core.Audio.IAudioData.html
  name: IAudioData
  nameWithType: IAudioData
  fullName: VRBuilder.Core.Audio.IAudioData
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: VRBuilder.Core.Audio
  commentId: N:VRBuilder.Core.Audio
  href: VRBuilder.html
  name: VRBuilder.Core.Audio
  nameWithType: VRBuilder.Core.Audio
  fullName: VRBuilder.Core.Audio
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Audio
    name: Audio
    href: VRBuilder.Core.Audio.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Audio
    name: Audio
    href: VRBuilder.Core.Audio.html
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  href: VRBuilder.Core.Configuration.IProcessAudioPlayer.html#VRBuilder_Core_Configuration_IProcessAudioPlayer_Stop
  name: Stop
  nameWithType: IProcessAudioPlayer.Stop
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  href: VRBuilder.Core.Configuration.IProcessAudioPlayer.html#VRBuilder_Core_Configuration_IProcessAudioPlayer_Reset
  name: Reset
  nameWithType: IProcessAudioPlayer.Reset
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
