### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.UI.BaseSettingsProvider
  commentId: T:VRBuilder.Editor.UI.BaseSettingsProvider
  id: BaseSettingsProvider
  parent: VRBuilder.Editor.UI
  children:
  - VRBuilder.Editor.UI.BaseSettingsProvider.#ctor(System.String,SettingsScope,System.Collections.Generic.IEnumerable{System.String})
  - VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  - VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  - VRBuilder.Editor.UI.BaseSettingsProvider.sections
  langs:
  - csharp
  - vb
  name: BaseSettingsProvider
  nameWithType: BaseSettingsProvider
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider
  type: Class
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: BaseSettingsProvider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
    startLine: 15
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nBase Settings provider which allows to inject additional sections which implement <xref href=\"VRBuilder.Editor.UI.IProjectSettingsSection\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public abstract class BaseSettingsProvider : SettingsProvider'
    content.vb: >-
      Public MustInherit Class BaseSettingsProvider
          Inherits SettingsProvider
  inheritance:
  - System.Object
  derivedClasses:
  - VRBuilder.Editor.Netcode.VoiceChat.VoiceChatSettingsProvider
  - VRBuilder.Editor.UI.LanguageSettingsProvider
  - VRBuilder.Editor.UI.SceneObjectGroupsSettingsProvider
  - VRBuilder.Editor.UI.SpectatorSettingsProvider
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.sections
  commentId: F:VRBuilder.Editor.UI.BaseSettingsProvider.sections
  id: sections
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  langs:
  - csharp
  - vb
  name: sections
  nameWithType: BaseSettingsProvider.sections
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.sections
  type: Field
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: sections
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
    startLine: 17
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: protected List<IProjectSettingsSection> sections
    return:
      type: System.Collections.Generic.List{VRBuilder.Editor.UI.IProjectSettingsSection}
    content.vb: Protected sections As List(Of IProjectSettingsSection)
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.#ctor(System.String,SettingsScope,System.Collections.Generic.IEnumerable{System.String})
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.#ctor(System.String,SettingsScope,System.Collections.Generic.IEnumerable{System.String})
  id: '#ctor(System.String,SettingsScope,System.Collections.Generic.IEnumerable{System.String})'
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  langs:
  - csharp
  - vb
  name: BaseSettingsProvider(String, SettingsScope, IEnumerable<String>)
  nameWithType: BaseSettingsProvider.BaseSettingsProvider(String, SettingsScope, IEnumerable<String>)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.BaseSettingsProvider(System.String, SettingsScope, System.Collections.Generic.IEnumerable<System.String>)
  type: Constructor
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
    startLine: 19
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: protected BaseSettingsProvider(string path, SettingsScope scopes, IEnumerable<string> keywords = null)
    parameters:
    - id: path
      type: System.String
    - id: scopes
      type: SettingsScope
    - id: keywords
      type: System.Collections.Generic.IEnumerable{System.String}
    content.vb: Protected Sub New(path As String, scopes As SettingsScope, keywords As IEnumerable(Of String) = Nothing)
  overload: VRBuilder.Editor.UI.BaseSettingsProvider.#ctor*
  nameWithType.vb: BaseSettingsProvider.BaseSettingsProvider(String, SettingsScope, IEnumerable(Of String))
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
  fullName.vb: VRBuilder.Editor.UI.BaseSettingsProvider.BaseSettingsProvider(System.String, SettingsScope, System.Collections.Generic.IEnumerable(Of System.String))
  name.vb: BaseSettingsProvider(String, SettingsScope, IEnumerable(Of String))
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  id: OnGUI(System.String)
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  langs:
  - csharp
  - vb
  name: OnGUI(String)
  nameWithType: BaseSettingsProvider.OnGUI(String)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnGUI
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
    startLine: 36
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nDraw call.\n"
  example: []
  syntax:
    content: public override void OnGUI(string searchContext)
    parameters:
    - id: searchContext
      type: System.String
    content.vb: Public Overrides Sub OnGUI(searchContext As String)
  overload: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  id: InternalDraw(System.String)
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  langs:
  - csharp
  - vb
  name: InternalDraw(String)
  nameWithType: BaseSettingsProvider.InternalDraw(String)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InternalDraw
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/BaseSettingsProvider.cs
    startLine: 56
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nYour draw implementation, will be drawn above the injected sections.\n"
  example: []
  syntax:
    content: protected abstract void InternalDraw(string searchContext)
    parameters:
    - id: searchContext
      type: System.String
    content.vb: Protected MustOverride Sub InternalDraw(searchContext As String)
  overload: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw*
  modifiers.csharp:
  - protected
  - abstract
  modifiers.vb:
  - Protected
  - MustOverride
references:
- uid: VRBuilder.Editor.UI.IProjectSettingsSection
  commentId: T:VRBuilder.Editor.UI.IProjectSettingsSection
  parent: VRBuilder.Editor.UI
  name: IProjectSettingsSection
  nameWithType: IProjectSettingsSection
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection
- uid: VRBuilder.Editor.UI
  commentId: N:VRBuilder.Editor.UI
  name: VRBuilder.Editor.UI
  nameWithType: VRBuilder.Editor.UI
  fullName: VRBuilder.Editor.UI
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.List{VRBuilder.Editor.UI.IProjectSettingsSection}
  commentId: T:System.Collections.Generic.List{VRBuilder.Editor.UI.IProjectSettingsSection}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<IProjectSettingsSection>
  nameWithType: List<IProjectSettingsSection>
  fullName: System.Collections.Generic.List<VRBuilder.Editor.UI.IProjectSettingsSection>
  nameWithType.vb: List(Of IProjectSettingsSection)
  fullName.vb: System.Collections.Generic.List(Of VRBuilder.Editor.UI.IProjectSettingsSection)
  name.vb: List(Of IProjectSettingsSection)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: VRBuilder.Editor.UI.IProjectSettingsSection
    name: IProjectSettingsSection
    nameWithType: IProjectSettingsSection
    fullName: VRBuilder.Editor.UI.IProjectSettingsSection
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: VRBuilder.Editor.UI.IProjectSettingsSection
    name: IProjectSettingsSection
    nameWithType: IProjectSettingsSection
    fullName: VRBuilder.Editor.UI.IProjectSettingsSection
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.#ctor*
  commentId: Overload:VRBuilder.Editor.UI.BaseSettingsProvider.#ctor
  name: BaseSettingsProvider
  nameWithType: BaseSettingsProvider.BaseSettingsProvider
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.BaseSettingsProvider
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SettingsScope
  commentId: '!:SettingsScope'
  isExternal: true
  name: SettingsScope
  nameWithType: SettingsScope
  fullName: SettingsScope
- uid: System.Collections.Generic.IEnumerable{System.String}
  commentId: T:System.Collections.Generic.IEnumerable{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<String>
  nameWithType: IEnumerable<String>
  fullName: System.Collections.Generic.IEnumerable<System.String>
  nameWithType.vb: IEnumerable(Of String)
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.String)
  name.vb: IEnumerable(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI*
  commentId: Overload:VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI
  name: OnGUI
  nameWithType: BaseSettingsProvider.OnGUI
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw*
  commentId: Overload:VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw
  name: InternalDraw
  nameWithType: BaseSettingsProvider.InternalDraw
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw
