### YamlMime:ManagedReference
items:
- uid: VRBuilder.XRInteraction.User.InteractorLayerConfigurator
  commentId: T:VRBuilder.XRInteraction.User.InteractorLayerConfigurator
  id: InteractorLayerConfigurator
  parent: VRBuilder.XRInteraction.User
  children:
  - VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers(System.String,System.String)
  - VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet
  langs:
  - csharp
  - vb
  name: InteractorLayerConfigurator
  nameWithType: InteractorLayerConfigurator
  fullName: VRBuilder.XRInteraction.User.InteractorLayerConfigurator
  type: Class
  source:
    remote:
      path: Source/XR-Interaction-Component/Source/Runtime/User/InteractorLayerConfigurator.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InteractorLayerConfigurator
    path: ../../Assets/MindPort/VR Builder/Core/Source/XR-Interaction-Component/Source/Runtime/User/InteractorLayerConfigurator.cs
    startLine: 11
  assemblies:
  - VRBuilder.XRInteraction
  namespace: VRBuilder.XRInteraction.User
  summary: "\nConfigures interaction and/or raycast layers of a list of interactors to layers\nwith the specified names.\n"
  example: []
  syntax:
    content: 'public class InteractorLayerConfigurator : MonoBehaviour, ILayerConfigurator'
    content.vb: >-
      Public Class InteractorLayerConfigurator
          Inherits MonoBehaviour
          Implements ILayerConfigurator
  inheritance:
  - System.Object
  implements:
  - VRBuilder.Core.Setup.ILayerConfigurator
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet
  commentId: P:VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet
  id: LayerSet
  parent: VRBuilder.XRInteraction.User.InteractorLayerConfigurator
  langs:
  - csharp
  - vb
  name: LayerSet
  nameWithType: InteractorLayerConfigurator.LayerSet
  fullName: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet
  type: Property
  source:
    remote:
      path: Source/XR-Interaction-Component/Source/Runtime/User/InteractorLayerConfigurator.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: LayerSet
    path: ../../Assets/MindPort/VR Builder/Core/Source/XR-Interaction-Component/Source/Runtime/User/InteractorLayerConfigurator.cs
    startLine: 22
  assemblies:
  - VRBuilder.XRInteraction
  namespace: VRBuilder.XRInteraction.User
  summary: "\nThe layer set to be used on this configurator.\n"
  example: []
  syntax:
    content: public LayerSet LayerSet { get; }
    parameters: []
    return:
      type: VRBuilder.Core.Setup.LayerSet
    content.vb: Public ReadOnly Property LayerSet As LayerSet
  overload: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet*
  implements:
  - VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers(System.String,System.String)
  commentId: M:VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers(System.String,System.String)
  id: ConfigureLayers(System.String,System.String)
  parent: VRBuilder.XRInteraction.User.InteractorLayerConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureLayers(String, String)
  nameWithType: InteractorLayerConfigurator.ConfigureLayers(String, String)
  fullName: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers(System.String, System.String)
  type: Method
  source:
    remote:
      path: Source/XR-Interaction-Component/Source/Runtime/User/InteractorLayerConfigurator.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ConfigureLayers
    path: ../../Assets/MindPort/VR Builder/Core/Source/XR-Interaction-Component/Source/Runtime/User/InteractorLayerConfigurator.cs
    startLine: 25
  assemblies:
  - VRBuilder.XRInteraction
  namespace: VRBuilder.XRInteraction.User
  summary: "\nSet up the layer masks to the specified layer names.\n"
  example: []
  syntax:
    content: public void ConfigureLayers(string interactionLayerName, string raycastLayerName)
    parameters:
    - id: interactionLayerName
      type: System.String
    - id: raycastLayerName
      type: System.String
    content.vb: Public Sub ConfigureLayers(interactionLayerName As String, raycastLayerName As String)
  overload: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers*
  implements:
  - VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VRBuilder.XRInteraction.User
  commentId: N:VRBuilder.XRInteraction.User
  name: VRBuilder.XRInteraction.User
  nameWithType: VRBuilder.XRInteraction.User
  fullName: VRBuilder.XRInteraction.User
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.Core.Setup.ILayerConfigurator
  commentId: T:VRBuilder.Core.Setup.ILayerConfigurator
  parent: VRBuilder.Core.Setup
  name: ILayerConfigurator
  nameWithType: ILayerConfigurator
  fullName: VRBuilder.Core.Setup.ILayerConfigurator
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Setup
  commentId: N:VRBuilder.Core.Setup
  name: VRBuilder.Core.Setup
  nameWithType: VRBuilder.Core.Setup
  fullName: VRBuilder.Core.Setup
- uid: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet*
  commentId: Overload:VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet
  name: LayerSet
  nameWithType: InteractorLayerConfigurator.LayerSet
  fullName: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.LayerSet
- uid: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  commentId: P:VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
  parent: VRBuilder.Core.Setup.ILayerConfigurator
  name: LayerSet
  nameWithType: ILayerConfigurator.LayerSet
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.LayerSet
- uid: VRBuilder.Core.Setup.LayerSet
  commentId: T:VRBuilder.Core.Setup.LayerSet
  parent: VRBuilder.Core.Setup
  name: LayerSet
  nameWithType: LayerSet
  fullName: VRBuilder.Core.Setup.LayerSet
- uid: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers*
  commentId: Overload:VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers
  name: ConfigureLayers
  nameWithType: InteractorLayerConfigurator.ConfigureLayers
  fullName: VRBuilder.XRInteraction.User.InteractorLayerConfigurator.ConfigureLayers
- uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  commentId: M:VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
  parent: VRBuilder.Core.Setup.ILayerConfigurator
  isExternal: true
  name: ConfigureLayers(String, String)
  nameWithType: ILayerConfigurator.ConfigureLayers(String, String)
  fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String, System.String)
  spec.csharp:
  - uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
    name: ConfigureLayers
    nameWithType: ILayerConfigurator.ConfigureLayers
    fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers(System.String,System.String)
    name: ConfigureLayers
    nameWithType: ILayerConfigurator.ConfigureLayers
    fullName: VRBuilder.Core.Setup.ILayerConfigurator.ConfigureLayers
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
