### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings
  commentId: T:VRBuilder.Editor.Settings.BuilderProjectSettings
  id: BuilderProjectSettings
  parent: VRBuilder.Editor.Settings
  children:
  - VRBuilder.Editor.Settings.BuilderProjectSettings.IsFirstTimeStarted
  - VRBuilder.Editor.Settings.BuilderProjectSettings.Load
  - VRBuilder.Editor.Settings.BuilderProjectSettings.OpenXRControllerProfiles
  - VRBuilder.Editor.Settings.BuilderProjectSettings.ProjectBuilderVersion
  - VRBuilder.Editor.Settings.BuilderProjectSettings.Save
  - VRBuilder.Editor.Settings.BuilderProjectSettings.XRSDKs
  langs:
  - csharp
  - vb
  name: BuilderProjectSettings
  nameWithType: BuilderProjectSettings
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings
  type: Class
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: BuilderProjectSettings
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 15
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  summary: "\nSettings for a VR Builder Unity project.\n"
  example: []
  syntax:
    content: 'public class BuilderProjectSettings : ScriptableObject'
    content.vb: >-
      Public Class BuilderProjectSettings
          Inherits ScriptableObject
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.IsFirstTimeStarted
  commentId: F:VRBuilder.Editor.Settings.BuilderProjectSettings.IsFirstTimeStarted
  id: IsFirstTimeStarted
  parent: VRBuilder.Editor.Settings.BuilderProjectSettings
  langs:
  - csharp
  - vb
  name: IsFirstTimeStarted
  nameWithType: BuilderProjectSettings.IsFirstTimeStarted
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.IsFirstTimeStarted
  type: Field
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsFirstTimeStarted
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 21
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  summary: "\nWas VR Builder imported and therefore started for the first time.\n"
  example: []
  syntax:
    content: public bool IsFirstTimeStarted
    return:
      type: System.Boolean
    content.vb: Public IsFirstTimeStarted As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.ProjectBuilderVersion
  commentId: F:VRBuilder.Editor.Settings.BuilderProjectSettings.ProjectBuilderVersion
  id: ProjectBuilderVersion
  parent: VRBuilder.Editor.Settings.BuilderProjectSettings
  langs:
  - csharp
  - vb
  name: ProjectBuilderVersion
  nameWithType: BuilderProjectSettings.ProjectBuilderVersion
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.ProjectBuilderVersion
  type: Field
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ProjectBuilderVersion
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 27
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  summary: "\nBuilder version used last time this was checked.\n"
  example: []
  syntax:
    content: public string ProjectBuilderVersion
    return:
      type: System.String
    content.vb: Public ProjectBuilderVersion As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.OpenXRControllerProfiles
  commentId: F:VRBuilder.Editor.Settings.BuilderProjectSettings.OpenXRControllerProfiles
  id: OpenXRControllerProfiles
  parent: VRBuilder.Editor.Settings.BuilderProjectSettings
  langs:
  - csharp
  - vb
  name: OpenXRControllerProfiles
  nameWithType: BuilderProjectSettings.OpenXRControllerProfiles
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.OpenXRControllerProfiles
  type: Field
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OpenXRControllerProfiles
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 30
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  syntax:
    content: public List<string> OpenXRControllerProfiles
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public OpenXRControllerProfiles As List(Of String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.XRSDKs
  commentId: F:VRBuilder.Editor.Settings.BuilderProjectSettings.XRSDKs
  id: XRSDKs
  parent: VRBuilder.Editor.Settings.BuilderProjectSettings
  langs:
  - csharp
  - vb
  name: XRSDKs
  nameWithType: BuilderProjectSettings.XRSDKs
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.XRSDKs
  type: Field
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: XRSDKs
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 33
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  syntax:
    content: public List<XRLoaderHelper.XRSDK> XRSDKs
    return:
      type: System.Collections.Generic.List{VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK}
    content.vb: Public XRSDKs As List(Of XRLoaderHelper.XRSDK)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.Load
  commentId: M:VRBuilder.Editor.Settings.BuilderProjectSettings.Load
  id: Load
  parent: VRBuilder.Editor.Settings.BuilderProjectSettings
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: BuilderProjectSettings.Load()
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.Load()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Load
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 39
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  summary: "\nLoads the VR Builder settings for this Unity project from Resources.\n"
  example: []
  syntax:
    content: public static BuilderProjectSettings Load()
    return:
      type: VRBuilder.Editor.Settings.BuilderProjectSettings
      description: Settings
    content.vb: Public Shared Function Load As BuilderProjectSettings
  overload: VRBuilder.Editor.Settings.BuilderProjectSettings.Load*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.Save
  commentId: M:VRBuilder.Editor.Settings.BuilderProjectSettings.Save
  id: Save
  parent: VRBuilder.Editor.Settings.BuilderProjectSettings
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: BuilderProjectSettings.Save()
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.Save()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/BuilderProjectSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Save
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/BuilderProjectSettings.cs
    startLine: 70
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Settings
  summary: "\nSaves the VR Builder settings.\n"
  example: []
  syntax:
    content: public void Save()
    content.vb: Public Sub Save
  overload: VRBuilder.Editor.Settings.BuilderProjectSettings.Save*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VRBuilder.Editor.Settings
  commentId: N:VRBuilder.Editor.Settings
  name: VRBuilder.Editor.Settings
  nameWithType: VRBuilder.Editor.Settings
  fullName: VRBuilder.Editor.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Collections.Generic.List{VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK}
  commentId: T:System.Collections.Generic.List{VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<XRLoaderHelper.XRSDK>
  nameWithType: List<XRLoaderHelper.XRSDK>
  fullName: System.Collections.Generic.List<VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK>
  nameWithType.vb: List(Of XRLoaderHelper.XRSDK)
  fullName.vb: System.Collections.Generic.List(Of VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK)
  name.vb: List(Of XRLoaderHelper.XRSDK)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK
    name: XRLoaderHelper.XRSDK
    nameWithType: XRLoaderHelper.XRSDK
    fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK
    name: XRLoaderHelper.XRSDK
    nameWithType: XRLoaderHelper.XRSDK
    fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRSDK
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.Load*
  commentId: Overload:VRBuilder.Editor.Settings.BuilderProjectSettings.Load
  name: Load
  nameWithType: BuilderProjectSettings.Load
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.Load
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings
  commentId: T:VRBuilder.Editor.Settings.BuilderProjectSettings
  parent: VRBuilder.Editor.Settings
  name: BuilderProjectSettings
  nameWithType: BuilderProjectSettings
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings.Save*
  commentId: Overload:VRBuilder.Editor.Settings.BuilderProjectSettings.Save
  name: Save
  nameWithType: BuilderProjectSettings.Save
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings.Save
