### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  commentId: T:VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  id: IEditorConfigurationExtension
  parent: VRBuilder.Editor.Configuration
  children:
  - VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  - VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  langs:
  - csharp
  - vb
  name: IEditorConfigurationExtension
  nameWithType: IEditorConfigurationExtension
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  type: Interface
  source:
    remote:
      path: Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IEditorConfigurationExtension
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
    startLine: 12
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: "\nInterface for editor configuration extension definition.\n"
  example: []
  syntax:
    content: public interface IEditorConfigurationExtension
    content.vb: Public Interface IEditorConfigurationExtension
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  commentId: P:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  id: RequiredMenuItems
  parent: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  langs:
  - csharp
  - vb
  name: RequiredMenuItems
  nameWithType: IEditorConfigurationExtension.RequiredMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RequiredMenuItems
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
    startLine: 17
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: "\nMenu items required by this configuration.\n"
  example: []
  syntax:
    content: IEnumerable<Type> RequiredMenuItems { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
    content.vb: ReadOnly Property RequiredMenuItems As IEnumerable(Of Type)
  overload: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  commentId: P:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  id: DisabledMenuItems
  parent: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  langs:
  - csharp
  - vb
  name: DisabledMenuItems
  nameWithType: IEditorConfigurationExtension.DisabledMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: DisabledMenuItems
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
    startLine: 22
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: "\nMenu items disabled by this configuration.\n"
  example: []
  syntax:
    content: IEnumerable<Type> DisabledMenuItems { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
    content.vb: ReadOnly Property DisabledMenuItems As IEnumerable(Of Type)
  overload: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems*
  commentId: Overload:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  name: RequiredMenuItems
  nameWithType: IEditorConfigurationExtension.RequiredMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
- uid: System.Collections.Generic.IEnumerable{System.Type}
  commentId: T:System.Collections.Generic.IEnumerable{System.Type}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<Type>
  nameWithType: IEnumerable<Type>
  fullName: System.Collections.Generic.IEnumerable<System.Type>
  nameWithType.vb: IEnumerable(Of Type)
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.Type)
  name.vb: IEnumerable(Of Type)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems*
  commentId: Overload:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  name: DisabledMenuItems
  nameWithType: IEditorConfigurationExtension.DisabledMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
