### YamlMime:ManagedReference
items:
- uid: VRBuilder.ProcessController.IConfigurableProcessController
  commentId: T:VRBuilder.ProcessController.IConfigurableProcessController
  id: IConfigurableProcessController
  parent: VRBuilder.ProcessController
  children:
  - VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  langs:
  - csharp
  - vb
  name: IConfigurableProcessController
  nameWithType: IConfigurableProcessController
  fullName: VRBuilder.ProcessController.IConfigurableProcessController
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IConfigurableProcessController
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
    startLine: 5
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.ProcessController
  summary: "\nInterface for a process controller that can be configured in the setup object.\n"
  example: []
  syntax:
    content: public interface IConfigurableProcessController
    content.vb: Public Interface IConfigurableProcessController
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  commentId: P:VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  id: AutoStartProcess
  parent: VRBuilder.ProcessController.IConfigurableProcessController
  langs:
  - csharp
  - vb
  name: AutoStartProcess
  nameWithType: IConfigurableProcessController.AutoStartProcess
  fullName: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: AutoStartProcess
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
    startLine: 10
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.ProcessController
  summary: "\nIf true, the process will start automatically as soon as the process controller is loaded.\n"
  example: []
  syntax:
    content: bool AutoStartProcess { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property AutoStartProcess As Boolean
  overload: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess*
  modifiers.csharp:
  - get
  - set
references:
- uid: VRBuilder.ProcessController
  commentId: N:VRBuilder.ProcessController
  name: VRBuilder.ProcessController
  nameWithType: VRBuilder.ProcessController
  fullName: VRBuilder.ProcessController
- uid: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess*
  commentId: Overload:VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  name: AutoStartProcess
  nameWithType: IConfigurableProcessController.AutoStartProcess
  fullName: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
