### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer
  commentId: T:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer
  id: JsonEditorConfigurationSerializer
  parent: VRBuilder.Editor.Serialization
  children:
  - VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize(System.String)
  - VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize(VRBuilder.Editor.Configuration.AllowedMenuItemsSettings)
  - VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings
  langs:
  - csharp
  - vb
  name: JsonEditorConfigurationSerializer
  nameWithType: JsonEditorConfigurationSerializer
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer
  type: Class
  source:
    remote:
      path: Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: JsonEditorConfigurationSerializer
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
    startLine: 11
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Serialization
  syntax:
    content: public static class JsonEditorConfigurationSerializer
    content.vb: Public Module JsonEditorConfigurationSerializer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings
  commentId: P:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings
  id: SerializerSettings
  parent: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer
  langs:
  - csharp
  - vb
  name: SerializerSettings
  nameWithType: JsonEditorConfigurationSerializer.SerializerSettings
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SerializerSettings
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
    startLine: 18
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Serialization
  summary: Returns the json serializer settings used by the process editor configuration deserialization.
  example: []
  syntax:
    content: public static JsonSerializerSettings SerializerSettings { get; }
    parameters: []
    return:
      type: Newtonsoft.Json.JsonSerializerSettings
    content.vb: Public Shared ReadOnly Property SerializerSettings As JsonSerializerSettings
  overload: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings*
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize(VRBuilder.Editor.Configuration.AllowedMenuItemsSettings)
  commentId: M:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize(VRBuilder.Editor.Configuration.AllowedMenuItemsSettings)
  id: Serialize(VRBuilder.Editor.Configuration.AllowedMenuItemsSettings)
  parent: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer
  langs:
  - csharp
  - vb
  name: Serialize(AllowedMenuItemsSettings)
  nameWithType: JsonEditorConfigurationSerializer.Serialize(AllowedMenuItemsSettings)
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize(VRBuilder.Editor.Configuration.AllowedMenuItemsSettings)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Serialize
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
    startLine: 33
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Serialization
  syntax:
    content: public static string Serialize(AllowedMenuItemsSettings deserialized)
    parameters:
    - id: deserialized
      type: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
    return:
      type: System.String
    content.vb: Public Shared Function Serialize(deserialized As AllowedMenuItemsSettings) As String
  overload: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize*
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize(System.String)
  commentId: M:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize(System.String)
  id: Deserialize(System.String)
  parent: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer
  langs:
  - csharp
  - vb
  name: Deserialize(string)
  nameWithType: JsonEditorConfigurationSerializer.Deserialize(string)
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize(string)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Deserialize
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Serialization/JsonEditorConfigurationSerializer.cs
    startLine: 45
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Serialization
  syntax:
    content: public static AllowedMenuItemsSettings Deserialize(string serialized)
    parameters:
    - id: serialized
      type: System.String
    return:
      type: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
    content.vb: Public Shared Function Deserialize(serialized As String) As AllowedMenuItemsSettings
  overload: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize*
  nameWithType.vb: JsonEditorConfigurationSerializer.Deserialize(String)
  fullName.vb: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize(String)
  name.vb: Deserialize(String)
references:
- uid: VRBuilder.Editor.Serialization
  commentId: N:VRBuilder.Editor.Serialization
  href: VRBuilder.html
  name: VRBuilder.Editor.Serialization
  nameWithType: VRBuilder.Editor.Serialization
  fullName: VRBuilder.Editor.Serialization
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Serialization
    name: Serialization
    href: VRBuilder.Editor.Serialization.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Serialization
    name: Serialization
    href: VRBuilder.Editor.Serialization.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings*
  commentId: Overload:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings
  href: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.html#VRBuilder_Editor_Serialization_JsonEditorConfigurationSerializer_SerializerSettings
  name: SerializerSettings
  nameWithType: JsonEditorConfigurationSerializer.SerializerSettings
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.SerializerSettings
- uid: Newtonsoft.Json.JsonSerializerSettings
  commentId: T:Newtonsoft.Json.JsonSerializerSettings
  parent: Newtonsoft.Json
  isExternal: true
  name: JsonSerializerSettings
  nameWithType: JsonSerializerSettings
  fullName: Newtonsoft.Json.JsonSerializerSettings
- uid: Newtonsoft.Json
  commentId: N:Newtonsoft.Json
  isExternal: true
  name: Newtonsoft.Json
  nameWithType: Newtonsoft.Json
  fullName: Newtonsoft.Json
  spec.csharp:
  - uid: Newtonsoft
    name: Newtonsoft
    isExternal: true
  - name: .
  - uid: Newtonsoft.Json
    name: Json
    isExternal: true
  spec.vb:
  - uid: Newtonsoft
    name: Newtonsoft
    isExternal: true
  - name: .
  - uid: Newtonsoft.Json
    name: Json
    isExternal: true
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize*
  commentId: Overload:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize
  href: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.html#VRBuilder_Editor_Serialization_JsonEditorConfigurationSerializer_Serialize_VRBuilder_Editor_Configuration_AllowedMenuItemsSettings_
  name: Serialize
  nameWithType: JsonEditorConfigurationSerializer.Serialize
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Serialize
- uid: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
  commentId: T:VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
  parent: VRBuilder.Editor.Configuration
  href: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings.html
  name: AllowedMenuItemsSettings
  nameWithType: AllowedMenuItemsSettings
  fullName: VRBuilder.Editor.Configuration.AllowedMenuItemsSettings
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  href: VRBuilder.html
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Configuration
    name: Configuration
    href: VRBuilder.Editor.Configuration.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Configuration
    name: Configuration
    href: VRBuilder.Editor.Configuration.html
- uid: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize*
  commentId: Overload:VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize
  href: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.html#VRBuilder_Editor_Serialization_JsonEditorConfigurationSerializer_Deserialize_System_String_
  name: Deserialize
  nameWithType: JsonEditorConfigurationSerializer.Deserialize
  fullName: VRBuilder.Editor.Serialization.JsonEditorConfigurationSerializer.Deserialize
