### YamlMime:ManagedReference
items:
- uid: VRBuilder.ProcessController.IConfigurableProcessController
  commentId: T:VRBuilder.ProcessController.IConfigurableProcessController
  id: IConfigurableProcessController
  parent: VRBuilder.ProcessController
  children:
  - VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  langs:
  - csharp
  - vb
  name: IConfigurableProcessController
  nameWithType: IConfigurableProcessController
  fullName: VRBuilder.ProcessController.IConfigurableProcessController
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IConfigurableProcessController
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
    startLine: 5
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.ProcessController
  summary: Interface for a process controller that can be configured in the setup object.
  example: []
  syntax:
    content: public interface IConfigurableProcessController
    content.vb: Public Interface IConfigurableProcessController
- uid: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  commentId: P:VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  id: AutoStartProcess
  parent: VRBuilder.ProcessController.IConfigurableProcessController
  langs:
  - csharp
  - vb
  name: AutoStartProcess
  nameWithType: IConfigurableProcessController.AutoStartProcess
  fullName: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: AutoStartProcess
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/ProcessController/IConfigurableProcessController.cs
    startLine: 10
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.ProcessController
  summary: If true, the process will start automatically as soon as the process controller is loaded.
  example: []
  syntax:
    content: bool AutoStartProcess { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property AutoStartProcess As Boolean
  overload: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess*
references:
- uid: VRBuilder.ProcessController
  commentId: N:VRBuilder.ProcessController
  href: VRBuilder.html
  name: VRBuilder.ProcessController
  nameWithType: VRBuilder.ProcessController
  fullName: VRBuilder.ProcessController
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.ProcessController
    name: ProcessController
    href: VRBuilder.ProcessController.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.ProcessController
    name: ProcessController
    href: VRBuilder.ProcessController.html
- uid: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess*
  commentId: Overload:VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
  href: VRBuilder.ProcessController.IConfigurableProcessController.html#VRBuilder_ProcessController_IConfigurableProcessController_AutoStartProcess
  name: AutoStartProcess
  nameWithType: IConfigurableProcessController.AutoStartProcess
  fullName: VRBuilder.ProcessController.IConfigurableProcessController.AutoStartProcess
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
