### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  commentId: T:VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  id: IEditorConfigurationExtension
  parent: VRBuilder.Editor.Configuration
  children:
  - VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  - VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  langs:
  - csharp
  - vb
  name: IEditorConfigurationExtension
  nameWithType: IEditorConfigurationExtension
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  type: Interface
  source:
    remote:
      path: Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IEditorConfigurationExtension
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
    startLine: 12
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: Interface for editor configuration extension definition.
  example: []
  syntax:
    content: public interface IEditorConfigurationExtension
    content.vb: Public Interface IEditorConfigurationExtension
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  commentId: P:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  id: RequiredMenuItems
  parent: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  langs:
  - csharp
  - vb
  name: RequiredMenuItems
  nameWithType: IEditorConfigurationExtension.RequiredMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RequiredMenuItems
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
    startLine: 17
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: Menu items required by this configuration.
  example: []
  syntax:
    content: IEnumerable<Type> RequiredMenuItems { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
    content.vb: ReadOnly Property RequiredMenuItems As IEnumerable(Of Type)
  overload: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems*
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  commentId: P:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  id: DisabledMenuItems
  parent: VRBuilder.Editor.Configuration.IEditorConfigurationExtension
  langs:
  - csharp
  - vb
  name: DisabledMenuItems
  nameWithType: IEditorConfigurationExtension.DisabledMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
      branch: release/v4.2.0
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: DisabledMenuItems
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/IEditorConfigurationExtension.cs
    startLine: 22
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: Menu items disabled by this configuration.
  example: []
  syntax:
    content: IEnumerable<Type> DisabledMenuItems { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
    content.vb: ReadOnly Property DisabledMenuItems As IEnumerable(Of Type)
  overload: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems*
references:
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  href: VRBuilder.html
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Configuration
    name: Configuration
    href: VRBuilder.Editor.Configuration.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Configuration
    name: Configuration
    href: VRBuilder.Editor.Configuration.html
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems*
  commentId: Overload:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
  href: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.html#VRBuilder_Editor_Configuration_IEditorConfigurationExtension_RequiredMenuItems
  name: RequiredMenuItems
  nameWithType: IEditorConfigurationExtension.RequiredMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.RequiredMenuItems
- uid: System.Collections.Generic.IEnumerable{System.Type}
  commentId: T:System.Collections.Generic.IEnumerable{System.Type}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<Type>
  nameWithType: IEnumerable<Type>
  fullName: System.Collections.Generic.IEnumerable<System.Type>
  nameWithType.vb: IEnumerable(Of Type)
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.Type)
  name.vb: IEnumerable(Of Type)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: System.Type
    name: Type
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.type
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Type
    name: Type
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.type
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems*
  commentId: Overload:VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
  href: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.html#VRBuilder_Editor_Configuration_IEditorConfigurationExtension_DisabledMenuItems
  name: DisabledMenuItems
  nameWithType: IEditorConfigurationExtension.DisabledMenuItems
  fullName: VRBuilder.Editor.Configuration.IEditorConfigurationExtension.DisabledMenuItems
