### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject`1
  id: SettingsObject`1
  parent: VRBuilder.Core.Runtime.Utils
  children:
  - VRBuilder.Core.Runtime.Utils.SettingsObject`1.Finalize
  - VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  - VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  langs:
  - csharp
  - vb
  name: SettingsObject<T>
  nameWithType: SettingsObject<T>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>
  type: Class
  source:
    remote:
      path: Source/Core/Runtime/Utils/SettingsObject.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SettingsObject
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Utils/SettingsObject.cs
    startLine: 16
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Runtime.Utils
  summary: "\nScriptableObject with additional load and save mechanic to make it a singleton.\n"
  example: []
  syntax:
    content: 'public class SettingsObject<T> : ScriptableObject where T : ScriptableObject, new()'
    typeParameters:
    - id: T
      description: The class itself
    content.vb: >-
      Public Class SettingsObject(Of T As {ScriptableObject, New})

          Inherits ScriptableObject
  inheritance:
  - System.Object
  derivedClasses:
  - VRBuilder.Core.Localization.LanguageSettings
  - VRBuilder.Core.Settings.InteractionSettings
  - VRBuilder.Core.Settings.SceneObjectGroups
  - VRBuilder.Core.Settings.SceneObjectTags
  - VRBuilder.Core.Utils.Logging.LifeCycleLoggingConfig
  - VRBuilder.Editor.Settings.InteractionComponentSettings
  - VRBuilder.Editor.XRInteraction.SnapZoneSettings
  - VRBuilder.Netcode.VoiceChat.VoiceChatSettings
  - VRBuilder.TextToSpeech.TextToSpeechConfiguration
  nameWithType.vb: SettingsObject(Of T)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T)
  name.vb: SettingsObject(Of T)
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  id: Instance
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: SettingsObject<T>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Instance
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Utils/SettingsObject.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Instance
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Utils/SettingsObject.cs
    startLine: 20
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Runtime.Utils
  syntax:
    content: public static T Instance { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Shared ReadOnly Property Instance As T
  overload: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance*
  nameWithType.vb: SettingsObject(Of T).Instance
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  id: Save
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: SettingsObject<T>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save()
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Utils/SettingsObject.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Save
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Utils/SettingsObject.cs
    startLine: 64
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Runtime.Utils
  summary: "\nSaves the VR Builder settings, only works in editor.\n"
  example: []
  syntax:
    content: public void Save()
    content.vb: Public Sub Save
  overload: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save*
  nameWithType.vb: SettingsObject(Of T).Save()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save()
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Finalize
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Finalize
  id: Finalize
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  langs:
  - csharp
  - vb
  name: Finalize()
  nameWithType: SettingsObject<T>.Finalize()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Finalize()
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Utils/SettingsObject.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Finalize
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Utils/SettingsObject.cs
    startLine: 73
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Runtime.Utils
  syntax:
    content: protected void Finalize()
    content.vb: Protected Sub Finalize
  overload: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Finalize*
  nameWithType.vb: SettingsObject(Of T).Finalize()
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Finalize()
references:
- uid: VRBuilder.Core.Runtime.Utils
  commentId: N:VRBuilder.Core.Runtime.Utils
  name: VRBuilder.Core.Runtime.Utils
  nameWithType: VRBuilder.Core.Runtime.Utils
  fullName: VRBuilder.Core.Runtime.Utils
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance*
  commentId: Overload:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<T>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Instance
  nameWithType.vb: SettingsObject(Of T).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Instance
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save*
  commentId: Overload:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save
  nameWithType: SettingsObject<T>.Save
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save
  nameWithType.vb: SettingsObject(Of T).Save
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Finalize*
  commentId: Overload:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Finalize
  name: Finalize
  nameWithType: SettingsObject<T>.Finalize
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Finalize
  nameWithType.vb: SettingsObject(Of T).Finalize
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Finalize
