### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Settings
  commentId: N:VRBuilder.Core.Settings
  id: VRBuilder.Core.Settings
  children:
  - VRBuilder.Core.Settings.InteractionSettings
  - VRBuilder.Core.Settings.SceneObjectGroups
  - VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup
  - VRBuilder.Core.Settings.SceneObjectTags
  - VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: VRBuilder.Core.Settings
  nameWithType: VRBuilder.Core.Settings
  fullName: VRBuilder.Core.Settings
  type: Namespace
  assemblies:
  - VRBuilder.Core
references:
- uid: VRBuilder.Core.Settings.InteractionSettings
  commentId: T:VRBuilder.Core.Settings.InteractionSettings
  href: VRBuilder.Core.Settings.InteractionSettings.html
  name: InteractionSettings
  nameWithType: InteractionSettings
  fullName: VRBuilder.Core.Settings.InteractionSettings
- uid: VRBuilder.Core.Settings.SceneObjectGroups
  commentId: T:VRBuilder.Core.Settings.SceneObjectGroups
  href: VRBuilder.Core.Settings.SceneObjectGroups.html
  name: SceneObjectGroups
  nameWithType: SceneObjectGroups
  fullName: VRBuilder.Core.Settings.SceneObjectGroups
- uid: VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup
  commentId: T:VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup
  parent: VRBuilder.Core.Settings
  href: VRBuilder.Core.Settings.SceneObjectGroups.html
  name: SceneObjectGroups.SceneObjectGroup
  nameWithType: SceneObjectGroups.SceneObjectGroup
  fullName: VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup
  spec.csharp:
  - uid: VRBuilder.Core.Settings.SceneObjectGroups
    name: SceneObjectGroups
    href: VRBuilder.Core.Settings.SceneObjectGroups.html
  - name: .
  - uid: VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup
    name: SceneObjectGroup
    href: VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup.html
  spec.vb:
  - uid: VRBuilder.Core.Settings.SceneObjectGroups
    name: SceneObjectGroups
    href: VRBuilder.Core.Settings.SceneObjectGroups.html
  - name: .
  - uid: VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup
    name: SceneObjectGroup
    href: VRBuilder.Core.Settings.SceneObjectGroups.SceneObjectGroup.html
- uid: VRBuilder.Core.Settings.SceneObjectTags
  commentId: T:VRBuilder.Core.Settings.SceneObjectTags
  href: VRBuilder.Core.Settings.SceneObjectTags.html
  name: SceneObjectTags
  nameWithType: SceneObjectTags
  fullName: VRBuilder.Core.Settings.SceneObjectTags
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag
  commentId: T:VRBuilder.Core.Settings.SceneObjectTags.Tag
  parent: VRBuilder.Core.Settings
  href: VRBuilder.Core.Settings.SceneObjectTags.html
  name: SceneObjectTags.Tag
  nameWithType: SceneObjectTags.Tag
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag
  spec.csharp:
  - uid: VRBuilder.Core.Settings.SceneObjectTags
    name: SceneObjectTags
    href: VRBuilder.Core.Settings.SceneObjectTags.html
  - name: .
  - uid: VRBuilder.Core.Settings.SceneObjectTags.Tag
    name: Tag
    href: VRBuilder.Core.Settings.SceneObjectTags.Tag.html
  spec.vb:
  - uid: VRBuilder.Core.Settings.SceneObjectTags
    name: SceneObjectTags
    href: VRBuilder.Core.Settings.SceneObjectTags.html
  - name: .
  - uid: VRBuilder.Core.Settings.SceneObjectTags.Tag
    name: Tag
    href: VRBuilder.Core.Settings.SceneObjectTags.Tag.html
- uid: VRBuilder.Core.Settings
  commentId: N:VRBuilder.Core.Settings
  href: VRBuilder.html
  name: VRBuilder.Core.Settings
  nameWithType: VRBuilder.Core.Settings
  fullName: VRBuilder.Core.Settings
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Settings
    name: Settings
    href: VRBuilder.Core.Settings.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Settings
    name: Settings
    href: VRBuilder.Core.Settings.html
