### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  commentId: T:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  id: RuntimeConfiguratorEditor
  parent: VRBuilder.Editor.Configuration
  children:
  - VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty
  - VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable
  - VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: RuntimeConfiguratorEditor
  nameWithType: RuntimeConfiguratorEditor
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  type: Class
  source:
    remote:
      path: Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RuntimeConfiguratorEditor
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
    startLine: 23
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: "\nCustom editor for choosing the process configuration in the Unity game object inspector.\n"
  example: []
  syntax:
    content: 'public class RuntimeConfiguratorEditor : Editor'
    content.vb: >-
      Public Class RuntimeConfiguratorEditor
          Inherits Editor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty
  commentId: M:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty
  id: IsProcessListEmpty
  parent: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  langs:
  - csharp
  - vb
  name: IsProcessListEmpty()
  nameWithType: RuntimeConfiguratorEditor.IsProcessListEmpty()
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsProcessListEmpty
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
    startLine: 55
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: "\nTrue when the process list is empty or missing.\n"
  example: []
  syntax:
    content: public static bool IsProcessListEmpty()
    return:
      type: System.Boolean
    content.vb: Public Shared Function IsProcessListEmpty As Boolean
  overload: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable
  commentId: M:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable
  id: OnEnable
  parent: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  langs:
  - csharp
  - vb
  name: OnEnable()
  nameWithType: RuntimeConfiguratorEditor.OnEnable()
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnEnable
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
    startLine: 65
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  syntax:
    content: protected void OnEnable()
    content.vb: Protected Sub OnEnable
  overload: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI
  commentId: M:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: RuntimeConfiguratorEditor.OnInspectorGUI()
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnInspectorGUI
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/RuntimeConfiguratorEditor.cs
    startLine: 82
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI
  overload: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty*
  commentId: Overload:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty
  name: IsProcessListEmpty
  nameWithType: RuntimeConfiguratorEditor.IsProcessListEmpty
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.IsProcessListEmpty
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable*
  commentId: Overload:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable
  name: OnEnable
  nameWithType: RuntimeConfiguratorEditor.OnEnable
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnEnable
- uid: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI*
  commentId: Overload:VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: RuntimeConfiguratorEditor.OnInspectorGUI
  fullName: VRBuilder.Editor.Configuration.RuntimeConfiguratorEditor.OnInspectorGUI
