### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings
  commentId: N:VRBuilder.Editor.TextToSpeech.UI.ProjectSettings
  id: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings
  children:
  - VRBuilder.Editor.TextToSpeech.UI.ProjectSettings.TextToSpeechSectionProvider
  langs:
  - csharp
  - vb
  name: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings
  nameWithType: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings
  fullName: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings
  type: Namespace
  assemblies:
  - VRBuilder.Editor.TextToSpeech
references:
- uid: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings.TextToSpeechSectionProvider
  commentId: T:VRBuilder.Editor.TextToSpeech.UI.ProjectSettings.TextToSpeechSectionProvider
  href: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings.TextToSpeechSectionProvider.html
  name: TextToSpeechSectionProvider
  nameWithType: TextToSpeechSectionProvider
  fullName: VRBuilder.Editor.TextToSpeech.UI.ProjectSettings.TextToSpeechSectionProvider
