### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  commentId: T:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  id: XRLoaderHelper.XRConfiguration
  parent: VRBuilder.Editor.XRUtils
  children:
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.None
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusLegacy
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusXR
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRLegacy
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRXR
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.WindowsMR
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRLegacy
  - VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRManagement
  langs:
  - csharp
  - vb
  name: XRLoaderHelper.XRConfiguration
  nameWithType: XRLoaderHelper.XRConfiguration
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  type: Enum
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: XRConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 45
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: public enum XRConfiguration
    content.vb: Public Enum XRConfiguration
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.None
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.None
  id: None
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: None
  nameWithType: XRLoaderHelper.XRConfiguration.None
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.None
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: None
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 47
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: None = 0
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRManagement
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRManagement
  id: XRManagement
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: XRManagement
  nameWithType: XRLoaderHelper.XRConfiguration.XRManagement
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRManagement
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: XRManagement
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 48
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: XRManagement = 1
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRLegacy
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRLegacy
  id: OpenVRLegacy
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: OpenVRLegacy
  nameWithType: XRLoaderHelper.XRConfiguration.OpenVRLegacy
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRLegacy
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OpenVRLegacy
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 49
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: OpenVRLegacy = 2
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusLegacy
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusLegacy
  id: OculusLegacy
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: OculusLegacy
  nameWithType: XRLoaderHelper.XRConfiguration.OculusLegacy
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusLegacy
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OculusLegacy
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 50
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: OculusLegacy = 3
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRXR
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRXR
  id: OpenVRXR
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: OpenVRXR
  nameWithType: XRLoaderHelper.XRConfiguration.OpenVRXR
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OpenVRXR
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OpenVRXR
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 51
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: OpenVRXR = 4
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusXR
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusXR
  id: OculusXR
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: OculusXR
  nameWithType: XRLoaderHelper.XRConfiguration.OculusXR
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.OculusXR
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OculusXR
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 52
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: OculusXR = 5
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.WindowsMR
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.WindowsMR
  id: WindowsMR
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: WindowsMR
  nameWithType: XRLoaderHelper.XRConfiguration.WindowsMR
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.WindowsMR
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: WindowsMR
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 53
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: WindowsMR = 6
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRLegacy
  commentId: F:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRLegacy
  id: XRLegacy
  parent: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  langs:
  - csharp
  - vb
  name: XRLegacy
  nameWithType: XRLoaderHelper.XRConfiguration.XRLegacy
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration.XRLegacy
  type: Field
  source:
    remote:
      path: Source/Core/Editor/XRUtils/XRLoaderHelper.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: XRLegacy
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/XRUtils/XRLoaderHelper.cs
    startLine: 54
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.XRUtils
  syntax:
    content: XRLegacy = 7
    return:
      type: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: VRBuilder.Editor.XRUtils
  commentId: N:VRBuilder.Editor.XRUtils
  name: VRBuilder.Editor.XRUtils
  nameWithType: VRBuilder.Editor.XRUtils
  fullName: VRBuilder.Editor.XRUtils
- uid: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  commentId: T:VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
  parent: VRBuilder.Editor.XRUtils
  name: XRLoaderHelper.XRConfiguration
  nameWithType: XRLoaderHelper.XRConfiguration
  fullName: VRBuilder.Editor.XRUtils.XRLoaderHelper.XRConfiguration
