### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  commentId: T:VRBuilder.Editor.Setup.ISceneSetupConfiguration
  id: ISceneSetupConfiguration
  parent: VRBuilder.Editor.Setup
  children:
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority
  - VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName
  langs:
  - csharp
  - vb
  name: ISceneSetupConfiguration
  nameWithType: ISceneSetupConfiguration
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  type: Interface
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ISceneSetupConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 7
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Defines the configuration for a particular scene setup.
  example: []
  syntax:
    content: public interface ISceneSetupConfiguration
    content.vb: Public Interface ISceneSetupConfiguration
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority
  id: Priority
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: ISceneSetupConfiguration.Priority
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Priority
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 12
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Priority of this configuration.
  example: []
  syntax:
    content: int Priority { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property Priority As Integer
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name
  id: Name
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ISceneSetupConfiguration.Name
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Name
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 17
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Display name of the configuration.
  example: []
  syntax:
    content: string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Name As String
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description
  id: Description
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: ISceneSetupConfiguration.Description
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Description
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 22
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Detailed description of the configuration.
  example: []
  syntax:
    content: string Description { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Description As String
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController
  id: DefaultProcessController
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: DefaultProcessController
  nameWithType: ISceneSetupConfiguration.DefaultProcessController
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: DefaultProcessController
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 27
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Default process controller to use in this configuration.
  example: []
  syntax:
    content: string DefaultProcessController { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property DefaultProcessController As String
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab
  id: DefaultConfettiPrefab
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: DefaultConfettiPrefab
  nameWithType: ISceneSetupConfiguration.DefaultConfettiPrefab
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: DefaultConfettiPrefab
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 32
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Default resources prefab to use for Confetti behavior.
  example: []
  syntax:
    content: string DefaultConfettiPrefab { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property DefaultConfettiPrefab As String
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName
  id: RuntimeConfigurationName
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: RuntimeConfigurationName
  nameWithType: ISceneSetupConfiguration.RuntimeConfigurationName
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: RuntimeConfigurationName
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 37
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Name of the runtime configuration to use.
  example: []
  syntax:
    content: string RuntimeConfigurationName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property RuntimeConfigurationName As String
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies
  commentId: P:VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies
  id: AllowedExtensionAssemblies
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: AllowedExtensionAssemblies
  nameWithType: ISceneSetupConfiguration.AllowedExtensionAssemblies
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: AllowedExtensionAssemblies
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 42
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Returns the names of the assemblies which contain allowed extensions.
  example: []
  syntax:
    content: IEnumerable<string> AllowedExtensionAssemblies { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.String}
    content.vb: ReadOnly Property AllowedExtensionAssemblies As IEnumerable(Of String)
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies*
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames
  commentId: M:VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames
  id: GetSetupNames
  parent: VRBuilder.Editor.Setup.ISceneSetupConfiguration
  langs:
  - csharp
  - vb
  name: GetSetupNames()
  nameWithType: ISceneSetupConfiguration.GetSetupNames()
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: GetSetupNames
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/Setup/ISceneSetupConfiguration.cs
    startLine: 47
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Setup
  summary: Gets the required scene setup actions for this configuration.
  example: []
  syntax:
    content: IEnumerable<string> GetSetupNames()
    return:
      type: System.Collections.Generic.IEnumerable{System.String}
    content.vb: Function GetSetupNames() As IEnumerable(Of String)
  overload: VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames*
references:
- uid: VRBuilder.Editor.Setup
  commentId: N:VRBuilder.Editor.Setup
  href: VRBuilder.html
  name: VRBuilder.Editor.Setup
  nameWithType: VRBuilder.Editor.Setup
  fullName: VRBuilder.Editor.Setup
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Setup
    name: Setup
    href: VRBuilder.Editor.Setup.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Setup
    name: Setup
    href: VRBuilder.Editor.Setup.html
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_Priority
  name: Priority
  nameWithType: ISceneSetupConfiguration.Priority
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Priority
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_Name
  name: Name
  nameWithType: ISceneSetupConfiguration.Name
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_Description
  name: Description
  nameWithType: ISceneSetupConfiguration.Description
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.Description
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_DefaultProcessController
  name: DefaultProcessController
  nameWithType: ISceneSetupConfiguration.DefaultProcessController
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultProcessController
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_DefaultConfettiPrefab
  name: DefaultConfettiPrefab
  nameWithType: ISceneSetupConfiguration.DefaultConfettiPrefab
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.DefaultConfettiPrefab
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_RuntimeConfigurationName
  name: RuntimeConfigurationName
  nameWithType: ISceneSetupConfiguration.RuntimeConfigurationName
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.RuntimeConfigurationName
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_AllowedExtensionAssemblies
  name: AllowedExtensionAssemblies
  nameWithType: ISceneSetupConfiguration.AllowedExtensionAssemblies
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.AllowedExtensionAssemblies
- uid: System.Collections.Generic.IEnumerable{System.String}
  commentId: T:System.Collections.Generic.IEnumerable{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<string>
  nameWithType: IEnumerable<string>
  fullName: System.Collections.Generic.IEnumerable<string>
  nameWithType.vb: IEnumerable(Of String)
  fullName.vb: System.Collections.Generic.IEnumerable(Of String)
  name.vb: IEnumerable(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames*
  commentId: Overload:VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames
  href: VRBuilder.Editor.Setup.ISceneSetupConfiguration.html#VRBuilder_Editor_Setup_ISceneSetupConfiguration_GetSetupNames
  name: GetSetupNames
  nameWithType: ISceneSetupConfiguration.GetSetupNames
  fullName: VRBuilder.Editor.Setup.ISceneSetupConfiguration.GetSetupNames
