### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer
  commentId: T:VRBuilder.Core.Configuration.IProcessAudioPlayer
  id: IProcessAudioPlayer
  parent: VRBuilder.Core.Configuration
  children:
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  - VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  langs:
  - csharp
  - vb
  name: IProcessAudioPlayer
  nameWithType: IProcessAudioPlayer
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IProcessAudioPlayer
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 8
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nInterface for the class playing sounds for the process, i.e. tts and play audio behaviors.\n"
  example: []
  syntax:
    content: public interface IProcessAudioPlayer
    content.vb: Public Interface IProcessAudioPlayer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  commentId: P:VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  id: FallbackAudioSource
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: FallbackAudioSource
  nameWithType: IProcessAudioPlayer.FallbackAudioSource
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: FallbackAudioSource
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 13
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nGets a fallback audio source. Used only for backwards compatibility.\n"
  example: []
  syntax:
    content: AudioSource FallbackAudioSource { get; }
    parameters: []
    return:
      type: UnityEngine.AudioSource
    content.vb: ReadOnly Property FallbackAudioSource As AudioSource
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  commentId: P:VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  id: IsPlaying
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: IsPlaying
  nameWithType: IProcessAudioPlayer.IsPlaying
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsPlaying
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 18
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nTrue if currently playing audio.\n"
  example: []
  syntax:
    content: bool IsPlaying { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsPlaying As Boolean
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  commentId: M:VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  id: PlayAudio(VRBuilder.Core.Audio.IAudioData,System.Single,System.Single)
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: PlayAudio(IAudioData, Single, Single)
  nameWithType: IProcessAudioPlayer.PlayAudio(IAudioData, Single, Single)
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio(VRBuilder.Core.Audio.IAudioData, System.Single, System.Single)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: PlayAudio
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 23
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nPlay the specified audio immediately with the set parameters.\n"
  example: []
  syntax:
    content: void PlayAudio(IAudioData audioData, float volume = 1F, float pitch = 1F)
    parameters:
    - id: audioData
      type: VRBuilder.Core.Audio.IAudioData
    - id: volume
      type: System.Single
    - id: pitch
      type: System.Single
    content.vb: Sub PlayAudio(audioData As IAudioData, volume As Single = 1F, pitch As Single = 1F)
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio*
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  commentId: M:VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  id: Stop
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: Stop()
  nameWithType: IProcessAudioPlayer.Stop()
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop()
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Stop
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 28
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nStops playing audio.\n"
  example: []
  syntax:
    content: void Stop()
    content.vb: Sub Stop
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop*
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  commentId: M:VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  id: Reset
  parent: VRBuilder.Core.Configuration.IProcessAudioPlayer
  langs:
  - csharp
  - vb
  name: Reset()
  nameWithType: IProcessAudioPlayer.Reset()
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset()
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Reset
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IProcessAudioPlayer.cs
    startLine: 33
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: "\nResets the player to its default settings.\n"
  example: []
  syntax:
    content: void Reset()
    content.vb: Sub Reset
  overload: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset*
references:
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
  name: FallbackAudioSource
  nameWithType: IProcessAudioPlayer.FallbackAudioSource
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.FallbackAudioSource
- uid: UnityEngine.AudioSource
  commentId: T:UnityEngine.AudioSource
  parent: UnityEngine
  isExternal: true
  name: AudioSource
  nameWithType: AudioSource
  fullName: UnityEngine.AudioSource
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
  name: IsPlaying
  nameWithType: IProcessAudioPlayer.IsPlaying
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.IsPlaying
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio
  name: PlayAudio
  nameWithType: IProcessAudioPlayer.PlayAudio
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.PlayAudio
- uid: VRBuilder.Core.Audio.IAudioData
  commentId: T:VRBuilder.Core.Audio.IAudioData
  parent: VRBuilder.Core.Audio
  name: IAudioData
  nameWithType: IAudioData
  fullName: VRBuilder.Core.Audio.IAudioData
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: VRBuilder.Core.Audio
  commentId: N:VRBuilder.Core.Audio
  name: VRBuilder.Core.Audio
  nameWithType: VRBuilder.Core.Audio
  fullName: VRBuilder.Core.Audio
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
  name: Stop
  nameWithType: IProcessAudioPlayer.Stop
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Stop
- uid: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset*
  commentId: Overload:VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
  name: Reset
  nameWithType: IProcessAudioPlayer.Reset
  fullName: VRBuilder.Core.Configuration.IProcessAudioPlayer.Reset
