### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Localization.LanguageSettings
  commentId: T:VRBuilder.Core.Localization.LanguageSettings
  id: LanguageSettings
  parent: VRBuilder.Core.Localization
  children:
  - VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage
  - VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale
  - VRBuilder.Core.Localization.LanguageSettings.ApplicationLanguage
  - VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString(System.String)
  langs:
  - csharp
  - vb
  name: LanguageSettings
  nameWithType: LanguageSettings
  fullName: VRBuilder.Core.Localization.LanguageSettings
  type: Class
  source:
    remote:
      path: Source/Core/Runtime/Localization/LanguageSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: LanguageSettings
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Localization/LanguageSettings.cs
    startLine: 14
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Localization
  summary: "\nLanguage settings for VR Builder.\n"
  example: []
  syntax:
    content: 'public class LanguageSettings : SettingsObject<LanguageSettings>'
    content.vb: >-
      Public Class LanguageSettings
          Inherits SettingsObject(Of LanguageSettings)
  inheritance:
  - System.Object
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}
  inheritedMembers:
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}.Instance
  - VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}.Save
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Core.Localization.LanguageSettings.ApplicationLanguage
  commentId: F:VRBuilder.Core.Localization.LanguageSettings.ApplicationLanguage
  id: ApplicationLanguage
  parent: VRBuilder.Core.Localization.LanguageSettings
  langs:
  - csharp
  - vb
  name: ApplicationLanguage
  nameWithType: LanguageSettings.ApplicationLanguage
  fullName: VRBuilder.Core.Localization.LanguageSettings.ApplicationLanguage
  type: Field
  source:
    remote:
      path: Source/Core/Runtime/Localization/LanguageSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ApplicationLanguage
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Localization/LanguageSettings.cs
    startLine: 19
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Localization
  summary: "\nLanguage which should be used if no localization settings are present.\n"
  example: []
  syntax:
    content: public string ApplicationLanguage
    return:
      type: System.String
    content.vb: Public ApplicationLanguage As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage
  commentId: P:VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage
  id: ActiveOrDefaultLanguage
  parent: VRBuilder.Core.Localization.LanguageSettings
  langs:
  - csharp
  - vb
  name: ActiveOrDefaultLanguage
  nameWithType: LanguageSettings.ActiveOrDefaultLanguage
  fullName: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Localization/LanguageSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ActiveOrDefaultLanguage
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Localization/LanguageSettings.cs
    startLine: 24
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Localization
  summary: "\nReturns the active or default language.\n"
  example: []
  syntax:
    content: public string ActiveOrDefaultLanguage { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ActiveOrDefaultLanguage As String
  overload: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale
  commentId: P:VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale
  id: ActiveOrDefaultLocale
  parent: VRBuilder.Core.Localization.LanguageSettings
  langs:
  - csharp
  - vb
  name: ActiveOrDefaultLocale
  nameWithType: LanguageSettings.ActiveOrDefaultLocale
  fullName: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Localization/LanguageSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: ActiveOrDefaultLocale
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Localization/LanguageSettings.cs
    startLine: 35
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Localization
  summary: "\nReturns the active or default locale.\n"
  example: []
  syntax:
    content: public Locale ActiveOrDefaultLocale { get; }
    parameters: []
    return:
      type: UnityEngine.Localization.Locale
    content.vb: Public ReadOnly Property ActiveOrDefaultLocale As Locale
  overload: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString(System.String)
  commentId: M:VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString(System.String)
  id: GetLocaleFromString(System.String)
  parent: VRBuilder.Core.Localization.LanguageSettings
  langs:
  - csharp
  - vb
  name: GetLocaleFromString(String)
  nameWithType: LanguageSettings.GetLocaleFromString(String)
  fullName: VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Localization/LanguageSettings.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: GetLocaleFromString
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Localization/LanguageSettings.cs
    startLine: 70
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Localization
  summary: "\nGet Locale object from a language or language code string.\n"
  example: []
  syntax:
    content: public Locale GetLocaleFromString(string languageOrCode)
    parameters:
    - id: languageOrCode
      type: System.String
      description: The language or language code string.
    return:
      type: UnityEngine.Localization.Locale
      description: The Locale object corresponding to the language code string or NULL.
    content.vb: Public Function GetLocaleFromString(languageOrCode As String) As Locale
  overload: VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VRBuilder.Core.Localization
  commentId: N:VRBuilder.Core.Localization
  name: VRBuilder.Core.Localization
  nameWithType: VRBuilder.Core.Localization
  fullName: VRBuilder.Core.Localization
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}
  parent: VRBuilder.Core.Runtime.Utils
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  name: SettingsObject<LanguageSettings>
  nameWithType: SettingsObject<LanguageSettings>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Localization.LanguageSettings>
  nameWithType.vb: SettingsObject(Of LanguageSettings)
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Localization.LanguageSettings)
  name.vb: SettingsObject(Of LanguageSettings)
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: <
    nameWithType: <
    fullName: <
  - uid: VRBuilder.Core.Localization.LanguageSettings
    name: LanguageSettings
    nameWithType: LanguageSettings
    fullName: VRBuilder.Core.Localization.LanguageSettings
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: VRBuilder.Core.Localization.LanguageSettings
    name: LanguageSettings
    nameWithType: LanguageSettings
    fullName: VRBuilder.Core.Localization.LanguageSettings
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}.Instance
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<LanguageSettings>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Localization.LanguageSettings>.Instance
  nameWithType.vb: SettingsObject(Of LanguageSettings).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Localization.LanguageSettings).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}.Save
  parent: VRBuilder.Core.Runtime.Utils.SettingsObject{VRBuilder.Core.Localization.LanguageSettings}
  definition: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save()
  nameWithType: SettingsObject<LanguageSettings>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Localization.LanguageSettings>.Save()
  nameWithType.vb: SettingsObject(Of LanguageSettings).Save()
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Localization.LanguageSettings).Save()
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject<LanguageSettings>.Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<VRBuilder.Core.Localization.LanguageSettings>.Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject(Of LanguageSettings).Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject(Of VRBuilder.Core.Localization.LanguageSettings).Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
  commentId: T:VRBuilder.Core.Runtime.Utils.SettingsObject`1
  name: SettingsObject<T>
  nameWithType: SettingsObject<T>
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>
  nameWithType.vb: SettingsObject(Of T)
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T)
  name.vb: SettingsObject(Of T)
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1
    name: SettingsObject
    nameWithType: SettingsObject
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Runtime.Utils
  commentId: N:VRBuilder.Core.Runtime.Utils
  name: VRBuilder.Core.Runtime.Utils
  nameWithType: VRBuilder.Core.Runtime.Utils
  fullName: VRBuilder.Core.Runtime.Utils
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  commentId: P:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Instance
  name: Instance
  nameWithType: SettingsObject<T>.Instance
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Instance
  nameWithType.vb: SettingsObject(Of T).Instance
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Instance
- uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  commentId: M:VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
  name: Save()
  nameWithType: SettingsObject<T>.Save()
  fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save()
  nameWithType.vb: SettingsObject(Of T).Save()
  fullName.vb: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save()
  spec.csharp:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject<T>.Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject<T>.Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Core.Runtime.Utils.SettingsObject`1.Save
    name: Save
    nameWithType: SettingsObject(Of T).Save
    fullName: VRBuilder.Core.Runtime.Utils.SettingsObject(Of T).Save
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage*
  commentId: Overload:VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage
  name: ActiveOrDefaultLanguage
  nameWithType: LanguageSettings.ActiveOrDefaultLanguage
  fullName: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLanguage
- uid: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale*
  commentId: Overload:VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale
  name: ActiveOrDefaultLocale
  nameWithType: LanguageSettings.ActiveOrDefaultLocale
  fullName: VRBuilder.Core.Localization.LanguageSettings.ActiveOrDefaultLocale
- uid: UnityEngine.Localization.Locale
  commentId: T:UnityEngine.Localization.Locale
  parent: UnityEngine.Localization
  name: Locale
  nameWithType: Locale
  fullName: UnityEngine.Localization.Locale
- uid: UnityEngine.Localization
  commentId: N:UnityEngine.Localization
  name: UnityEngine.Localization
  nameWithType: UnityEngine.Localization
  fullName: UnityEngine.Localization
- uid: VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString*
  commentId: Overload:VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString
  name: GetLocaleFromString
  nameWithType: LanguageSettings.GetLocaleFromString
  fullName: VRBuilder.Core.Localization.LanguageSettings.GetLocaleFromString
