### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.Modes
  commentId: N:VRBuilder.Core.Configuration.Modes
  id: VRBuilder.Core.Configuration.Modes
  children:
  - VRBuilder.Core.Configuration.Modes.BaseModeHandler
  - VRBuilder.Core.Configuration.Modes.BlacklistTypeRule`1
  - VRBuilder.Core.Configuration.Modes.IConfigurator
  - VRBuilder.Core.Configuration.Modes.IMode
  - VRBuilder.Core.Configuration.Modes.IModeData
  - VRBuilder.Core.Configuration.Modes.IModeHandler
  - VRBuilder.Core.Configuration.Modes.IOptional
  - VRBuilder.Core.Configuration.Modes.IRule`1
  - VRBuilder.Core.Configuration.Modes.ListTypeRule`2
  - VRBuilder.Core.Configuration.Modes.Mode
  - VRBuilder.Core.Configuration.Modes.ModeChangedEventArgs
  - VRBuilder.Core.Configuration.Modes.ModeParameter`1
  - VRBuilder.Core.Configuration.Modes.TypeRule`1
  - VRBuilder.Core.Configuration.Modes.WhitelistTypeRule`1
  langs:
  - csharp
  - vb
  name: VRBuilder.Core.Configuration.Modes
  nameWithType: VRBuilder.Core.Configuration.Modes
  fullName: VRBuilder.Core.Configuration.Modes
  type: Namespace
  assemblies:
  - VRBuilder.Core
references:
- uid: VRBuilder.Core.Configuration.Modes.TypeRule`1
  commentId: T:VRBuilder.Core.Configuration.Modes.TypeRule`1
  name: TypeRule<TValueBase>
  nameWithType: TypeRule<TValueBase>
  fullName: VRBuilder.Core.Configuration.Modes.TypeRule<TValueBase>
  nameWithType.vb: TypeRule(Of TValueBase)
  fullName.vb: VRBuilder.Core.Configuration.Modes.TypeRule(Of TValueBase)
  name.vb: TypeRule(Of TValueBase)
  spec.csharp:
  - uid: VRBuilder.Core.Configuration.Modes.TypeRule`1
    name: TypeRule
    nameWithType: TypeRule
    fullName: VRBuilder.Core.Configuration.Modes.TypeRule
  - name: <
    nameWithType: <
    fullName: <
  - name: TValueBase
    nameWithType: TValueBase
    fullName: TValueBase
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Configuration.Modes.TypeRule`1
    name: TypeRule
    nameWithType: TypeRule
    fullName: VRBuilder.Core.Configuration.Modes.TypeRule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TValueBase
    nameWithType: TValueBase
    fullName: TValueBase
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration.Modes.BaseModeHandler
  commentId: T:VRBuilder.Core.Configuration.Modes.BaseModeHandler
  name: BaseModeHandler
  nameWithType: BaseModeHandler
  fullName: VRBuilder.Core.Configuration.Modes.BaseModeHandler
- uid: VRBuilder.Core.Configuration.Modes.ListTypeRule`2
  commentId: T:VRBuilder.Core.Configuration.Modes.ListTypeRule`2
  name: ListTypeRule<TRecursive, TValueBase>
  nameWithType: ListTypeRule<TRecursive, TValueBase>
  fullName: VRBuilder.Core.Configuration.Modes.ListTypeRule<TRecursive, TValueBase>
  nameWithType.vb: ListTypeRule(Of TRecursive, TValueBase)
  fullName.vb: VRBuilder.Core.Configuration.Modes.ListTypeRule(Of TRecursive, TValueBase)
  name.vb: ListTypeRule(Of TRecursive, TValueBase)
  spec.csharp:
  - uid: VRBuilder.Core.Configuration.Modes.ListTypeRule`2
    name: ListTypeRule
    nameWithType: ListTypeRule
    fullName: VRBuilder.Core.Configuration.Modes.ListTypeRule
  - name: <
    nameWithType: <
    fullName: <
  - name: TRecursive
    nameWithType: TRecursive
    fullName: TRecursive
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValueBase
    nameWithType: TValueBase
    fullName: TValueBase
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Configuration.Modes.ListTypeRule`2
    name: ListTypeRule
    nameWithType: ListTypeRule
    fullName: VRBuilder.Core.Configuration.Modes.ListTypeRule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TRecursive
    nameWithType: TRecursive
    fullName: TRecursive
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValueBase
    nameWithType: TValueBase
    fullName: TValueBase
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule`1
  commentId: T:VRBuilder.Core.Configuration.Modes.BlacklistTypeRule`1
  name: BlacklistTypeRule<TBase>
  nameWithType: BlacklistTypeRule<TBase>
  fullName: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule<TBase>
  nameWithType.vb: BlacklistTypeRule(Of TBase)
  fullName.vb: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule(Of TBase)
  name.vb: BlacklistTypeRule(Of TBase)
  spec.csharp:
  - uid: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule`1
    name: BlacklistTypeRule
    nameWithType: BlacklistTypeRule
    fullName: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule
  - name: <
    nameWithType: <
    fullName: <
  - name: TBase
    nameWithType: TBase
    fullName: TBase
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule`1
    name: BlacklistTypeRule
    nameWithType: BlacklistTypeRule
    fullName: VRBuilder.Core.Configuration.Modes.BlacklistTypeRule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TBase
    nameWithType: TBase
    fullName: TBase
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration.Modes.IRule`1
  commentId: T:VRBuilder.Core.Configuration.Modes.IRule`1
  name: IRule<T>
  nameWithType: IRule<T>
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>
  nameWithType.vb: IRule(Of T)
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T)
  name.vb: IRule(Of T)
  spec.csharp:
  - uid: VRBuilder.Core.Configuration.Modes.IRule`1
    name: IRule
    nameWithType: IRule
    fullName: VRBuilder.Core.Configuration.Modes.IRule
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Configuration.Modes.IRule`1
    name: IRule
    nameWithType: IRule
    fullName: VRBuilder.Core.Configuration.Modes.IRule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration.Modes.IConfigurator
  commentId: T:VRBuilder.Core.Configuration.Modes.IConfigurator
  parent: VRBuilder.Core.Configuration.Modes
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: VRBuilder.Core.Configuration.Modes.IConfigurator
- uid: VRBuilder.Core.Configuration.Modes.IModeData
  commentId: T:VRBuilder.Core.Configuration.Modes.IModeData
  parent: VRBuilder.Core.Configuration.Modes
  name: IModeData
  nameWithType: IModeData
  fullName: VRBuilder.Core.Configuration.Modes.IModeData
- uid: VRBuilder.Core.Configuration.Modes.ModeChangedEventArgs
  commentId: T:VRBuilder.Core.Configuration.Modes.ModeChangedEventArgs
  name: ModeChangedEventArgs
  nameWithType: ModeChangedEventArgs
  fullName: VRBuilder.Core.Configuration.Modes.ModeChangedEventArgs
- uid: VRBuilder.Core.Configuration.Modes.Mode
  commentId: T:VRBuilder.Core.Configuration.Modes.Mode
  name: Mode
  nameWithType: Mode
  fullName: VRBuilder.Core.Configuration.Modes.Mode
- uid: VRBuilder.Core.Configuration.Modes.IOptional
  commentId: T:VRBuilder.Core.Configuration.Modes.IOptional
  parent: VRBuilder.Core.Configuration.Modes
  name: IOptional
  nameWithType: IOptional
  fullName: VRBuilder.Core.Configuration.Modes.IOptional
- uid: VRBuilder.Core.Configuration.Modes.ModeParameter`1
  commentId: T:VRBuilder.Core.Configuration.Modes.ModeParameter`1
  name: ModeParameter<T>
  nameWithType: ModeParameter<T>
  fullName: VRBuilder.Core.Configuration.Modes.ModeParameter<T>
  nameWithType.vb: ModeParameter(Of T)
  fullName.vb: VRBuilder.Core.Configuration.Modes.ModeParameter(Of T)
  name.vb: ModeParameter(Of T)
  spec.csharp:
  - uid: VRBuilder.Core.Configuration.Modes.ModeParameter`1
    name: ModeParameter
    nameWithType: ModeParameter
    fullName: VRBuilder.Core.Configuration.Modes.ModeParameter
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Configuration.Modes.ModeParameter`1
    name: ModeParameter
    nameWithType: ModeParameter
    fullName: VRBuilder.Core.Configuration.Modes.ModeParameter
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration.Modes.IMode
  commentId: T:VRBuilder.Core.Configuration.Modes.IMode
  parent: VRBuilder.Core.Configuration.Modes
  name: IMode
  nameWithType: IMode
  fullName: VRBuilder.Core.Configuration.Modes.IMode
- uid: VRBuilder.Core.Configuration.Modes.IModeHandler
  commentId: T:VRBuilder.Core.Configuration.Modes.IModeHandler
  parent: VRBuilder.Core.Configuration.Modes
  name: IModeHandler
  nameWithType: IModeHandler
  fullName: VRBuilder.Core.Configuration.Modes.IModeHandler
- uid: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule`1
  commentId: T:VRBuilder.Core.Configuration.Modes.WhitelistTypeRule`1
  name: WhitelistTypeRule<TBase>
  nameWithType: WhitelistTypeRule<TBase>
  fullName: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule<TBase>
  nameWithType.vb: WhitelistTypeRule(Of TBase)
  fullName.vb: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule(Of TBase)
  name.vb: WhitelistTypeRule(Of TBase)
  spec.csharp:
  - uid: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule`1
    name: WhitelistTypeRule
    nameWithType: WhitelistTypeRule
    fullName: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule
  - name: <
    nameWithType: <
    fullName: <
  - name: TBase
    nameWithType: TBase
    fullName: TBase
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule`1
    name: WhitelistTypeRule
    nameWithType: WhitelistTypeRule
    fullName: VRBuilder.Core.Configuration.Modes.WhitelistTypeRule
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TBase
    nameWithType: TBase
    fullName: TBase
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Core.Configuration.Modes
  commentId: N:VRBuilder.Core.Configuration.Modes
  name: VRBuilder.Core.Configuration.Modes
  nameWithType: VRBuilder.Core.Configuration.Modes
  fullName: VRBuilder.Core.Configuration.Modes
