### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider
  commentId: T:VRBuilder.Editor.UI.SpectatorSettingsProvider
  id: SpectatorSettingsProvider
  parent: VRBuilder.Editor.UI
  children:
  - VRBuilder.Editor.UI.SpectatorSettingsProvider.#ctor
  - VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw(System.String)
  - VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider
  langs:
  - csharp
  - vb
  name: SpectatorSettingsProvider
  nameWithType: SpectatorSettingsProvider
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider
  type: Class
  source:
    remote:
      path: Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: SpectatorSettingsProvider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
    startLine: 4
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: 'public class SpectatorSettingsProvider : BaseSettingsProvider'
    content.vb: >-
      Public Class SpectatorSettingsProvider
          Inherits BaseSettingsProvider
  inheritance:
  - System.Object
  - VRBuilder.Editor.UI.BaseSettingsProvider
  inheritedMembers:
  - VRBuilder.Editor.UI.BaseSettingsProvider.sections
  - VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider.#ctor
  commentId: M:VRBuilder.Editor.UI.SpectatorSettingsProvider.#ctor
  id: '#ctor'
  parent: VRBuilder.Editor.UI.SpectatorSettingsProvider
  langs:
  - csharp
  - vb
  name: SpectatorSettingsProvider()
  nameWithType: SpectatorSettingsProvider.SpectatorSettingsProvider()
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider.SpectatorSettingsProvider()
  type: Constructor
  source:
    remote:
      path: Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
    startLine: 8
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: public SpectatorSettingsProvider()
    content.vb: Public Sub New
  overload: VRBuilder.Editor.UI.SpectatorSettingsProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw(System.String)
  commentId: M:VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw(System.String)
  id: InternalDraw(System.String)
  parent: VRBuilder.Editor.UI.SpectatorSettingsProvider
  langs:
  - csharp
  - vb
  name: InternalDraw(String)
  nameWithType: SpectatorSettingsProvider.InternalDraw(String)
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: InternalDraw
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
    startLine: 12
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: protected override void InternalDraw(string searchContext)
    parameters:
    - id: searchContext
      type: System.String
    content.vb: Protected Overrides Sub InternalDraw(searchContext As String)
  overridden: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  overload: VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider
  commentId: M:VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider
  id: Provider
  parent: VRBuilder.Editor.UI.SpectatorSettingsProvider
  langs:
  - csharp
  - vb
  name: Provider()
  nameWithType: SpectatorSettingsProvider.Provider()
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Provider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/Spectator/SpectatorSettingsProvider.cs
    startLine: 16
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  syntax:
    content: public static SettingsProvider Provider()
    return:
      type: SettingsProvider
    content.vb: Public Shared Function Provider As SettingsProvider
  overload: VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: VRBuilder.Editor.UI
  commentId: N:VRBuilder.Editor.UI
  name: VRBuilder.Editor.UI
  nameWithType: VRBuilder.Editor.UI
  fullName: VRBuilder.Editor.UI
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VRBuilder.Editor.UI.BaseSettingsProvider
  commentId: T:VRBuilder.Editor.UI.BaseSettingsProvider
  parent: VRBuilder.Editor.UI
  name: BaseSettingsProvider
  nameWithType: BaseSettingsProvider
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.sections
  commentId: F:VRBuilder.Editor.UI.BaseSettingsProvider.sections
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  name: sections
  nameWithType: BaseSettingsProvider.sections
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.sections
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  isExternal: true
  name: OnGUI(String)
  nameWithType: BaseSettingsProvider.OnGUI(String)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
  spec.csharp:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
    name: OnGUI
    nameWithType: BaseSettingsProvider.OnGUI
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI(System.String)
    name: OnGUI
    nameWithType: BaseSettingsProvider.OnGUI
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.OnGUI
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider.#ctor*
  commentId: Overload:VRBuilder.Editor.UI.SpectatorSettingsProvider.#ctor
  name: SpectatorSettingsProvider
  nameWithType: SpectatorSettingsProvider.SpectatorSettingsProvider
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider.SpectatorSettingsProvider
- uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  commentId: M:VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  parent: VRBuilder.Editor.UI.BaseSettingsProvider
  isExternal: true
  name: InternalDraw(String)
  nameWithType: BaseSettingsProvider.InternalDraw(String)
  fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
  spec.csharp:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
    name: InternalDraw
    nameWithType: BaseSettingsProvider.InternalDraw
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw(System.String)
    name: InternalDraw
    nameWithType: BaseSettingsProvider.InternalDraw
    fullName: VRBuilder.Editor.UI.BaseSettingsProvider.InternalDraw
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw*
  commentId: Overload:VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw
  name: InternalDraw
  nameWithType: SpectatorSettingsProvider.InternalDraw
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider.InternalDraw
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider*
  commentId: Overload:VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider
  name: Provider
  nameWithType: SpectatorSettingsProvider.Provider
  fullName: VRBuilder.Editor.UI.SpectatorSettingsProvider.Provider
- uid: SettingsProvider
  isExternal: true
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: SettingsProvider
