### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.Modes.IRule`1
  commentId: T:VRBuilder.Core.Configuration.Modes.IRule`1
  id: IRule`1
  parent: VRBuilder.Core.Configuration.Modes
  children:
  - VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy(`0)
  langs:
  - csharp
  - vb
  name: IRule<T>
  nameWithType: IRule<T>
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/Modes/IRule.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IRule
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/Modes/IRule.cs
    startLine: 9
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration.Modes
  summary: "\nVery generic interface which allows to implement a rule similar to Linq.Where or SQL Filter.\n"
  example: []
  syntax:
    content: public interface IRule<T>
    typeParameters:
    - id: T
    content.vb: Public Interface IRule(Of T)
  nameWithType.vb: IRule(Of T)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T)
  name.vb: IRule(Of T)
- uid: VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy(`0)
  commentId: M:VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy(`0)
  id: IsQualifiedBy(`0)
  parent: VRBuilder.Core.Configuration.Modes.IRule`1
  langs:
  - csharp
  - vb
  name: IsQualifiedBy(T)
  nameWithType: IRule<T>.IsQualifiedBy(T)
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>.IsQualifiedBy(T)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Configuration/Modes/IRule.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsQualifiedBy
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/Modes/IRule.cs
    startLine: 15
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration.Modes
  summary: "\nChecks a given <code data-dev-comment-type=\"paramref\" class=\"paramref\">value</code> and returns true if this value qualifies the rule.\n"
  example: []
  syntax:
    content: bool IsQualifiedBy(T value)
    parameters:
    - id: value
      type: '{T}'
      description: The type which is checked.
    return:
      type: System.Boolean
    content.vb: Function IsQualifiedBy(value As T) As Boolean
  overload: VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy*
  nameWithType.vb: IRule(Of T).IsQualifiedBy(T)
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T).IsQualifiedBy(T)
references:
- uid: VRBuilder.Core.Configuration.Modes
  commentId: N:VRBuilder.Core.Configuration.Modes
  name: VRBuilder.Core.Configuration.Modes
  nameWithType: VRBuilder.Core.Configuration.Modes
  fullName: VRBuilder.Core.Configuration.Modes
- uid: VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy*
  commentId: Overload:VRBuilder.Core.Configuration.Modes.IRule`1.IsQualifiedBy
  name: IsQualifiedBy
  nameWithType: IRule<T>.IsQualifiedBy
  fullName: VRBuilder.Core.Configuration.Modes.IRule<T>.IsQualifiedBy
  nameWithType.vb: IRule(Of T).IsQualifiedBy
  fullName.vb: VRBuilder.Core.Configuration.Modes.IRule(Of T).IsQualifiedBy
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
