### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.UI.IProjectSettingsSection
  commentId: T:VRBuilder.Editor.UI.IProjectSettingsSection
  id: IProjectSettingsSection
  parent: VRBuilder.Editor.UI
  children:
  - VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  - VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  - VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  - VRBuilder.Editor.UI.IProjectSettingsSection.Title
  langs:
  - csharp
  - vb
  name: IProjectSettingsSection
  nameWithType: IProjectSettingsSection
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection
  type: Interface
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IProjectSettingsSection
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 11
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nAllows to inject a settings section into a setting provider.\n"
  example: []
  syntax:
    content: public interface IProjectSettingsSection
    content.vb: Public Interface IProjectSettingsSection
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Title
  commentId: P:VRBuilder.Editor.UI.IProjectSettingsSection.Title
  id: Title
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: Title
  nameWithType: IProjectSettingsSection.Title
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Title
  type: Property
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Title
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 16
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nTitle of this section.\n"
  example: []
  syntax:
    content: string Title { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Title As String
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.Title*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  commentId: P:VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  id: TargetPageProvider
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: TargetPageProvider
  nameWithType: IProjectSettingsSection.TargetPageProvider
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  type: Property
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: TargetPageProvider
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 21
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nType of the target setting provider.\n"
  example: []
  syntax:
    content: Type TargetPageProvider { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: ReadOnly Property TargetPageProvider As Type
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  commentId: P:VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  id: Priority
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: IProjectSettingsSection.Priority
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  type: Property
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Priority
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 26
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nDetermines the draw order, lower priority will be drawn first.\n"
  example: []
  syntax:
    content: int Priority { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property Priority As Integer
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.Priority*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  commentId: M:VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  id: OnGUI(System.String)
  parent: VRBuilder.Editor.UI.IProjectSettingsSection
  langs:
  - csharp
  - vb
  name: OnGUI(String)
  nameWithType: IProjectSettingsSection.OnGUI(String)
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
      branch: develop
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: OnGUI
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Editor/UI/ProjectSettings/IProjectSettingsSection.cs
    startLine: 31
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.UI
  summary: "\nYour draw call.\n"
  example: []
  syntax:
    content: void OnGUI(string searchContext)
    parameters:
    - id: searchContext
      type: System.String
    content.vb: Sub OnGUI(searchContext As String)
  overload: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI*
references:
- uid: VRBuilder.Editor.UI
  commentId: N:VRBuilder.Editor.UI
  name: VRBuilder.Editor.UI
  nameWithType: VRBuilder.Editor.UI
  fullName: VRBuilder.Editor.UI
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Title*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.Title
  name: Title
  nameWithType: IProjectSettingsSection.Title
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Title
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
  name: TargetPageProvider
  nameWithType: IProjectSettingsSection.TargetPageProvider
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.TargetPageProvider
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.Priority*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.Priority
  name: Priority
  nameWithType: IProjectSettingsSection.Priority
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.Priority
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI*
  commentId: Overload:VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI
  name: OnGUI
  nameWithType: IProjectSettingsSection.OnGUI
  fullName: VRBuilder.Editor.UI.IProjectSettingsSection.OnGUI
