### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Settings
  commentId: N:VRBuilder.Editor.Settings
  id: VRBuilder.Editor.Settings
  children:
  - VRBuilder.Editor.Settings.BuilderProjectSettings
  - VRBuilder.Editor.Settings.InteractionComponentSettings
  langs:
  - csharp
  - vb
  name: VRBuilder.Editor.Settings
  nameWithType: VRBuilder.Editor.Settings
  fullName: VRBuilder.Editor.Settings
  type: Namespace
  assemblies:
  - VRBuilder.Editor
references:
- uid: VRBuilder.Editor.Settings.BuilderProjectSettings
  commentId: T:VRBuilder.Editor.Settings.BuilderProjectSettings
  parent: VRBuilder.Editor.Settings
  name: BuilderProjectSettings
  nameWithType: BuilderProjectSettings
  fullName: VRBuilder.Editor.Settings.BuilderProjectSettings
- uid: VRBuilder.Editor.Settings.InteractionComponentSettings
  commentId: T:VRBuilder.Editor.Settings.InteractionComponentSettings
  name: InteractionComponentSettings
  nameWithType: InteractionComponentSettings
  fullName: VRBuilder.Editor.Settings.InteractionComponentSettings
- uid: VRBuilder.Editor.Settings
  commentId: N:VRBuilder.Editor.Settings
  name: VRBuilder.Editor.Settings
  nameWithType: VRBuilder.Editor.Settings
  fullName: VRBuilder.Editor.Settings
