### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.RestrictiveEnvironment
  commentId: N:VRBuilder.Core.RestrictiveEnvironment
  id: VRBuilder.Core.RestrictiveEnvironment
  children:
  - VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
  - VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
  - VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
  - VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
  langs:
  - csharp
  - vb
  name: VRBuilder.Core.RestrictiveEnvironment
  nameWithType: VRBuilder.Core.RestrictiveEnvironment
  fullName: VRBuilder.Core.RestrictiveEnvironment
  type: Namespace
  assemblies:
  - VRBuilder.Core
references:
- uid: VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
  href: VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling.html
  name: DefaultStepLockHandling
  nameWithType: DefaultStepLockHandling
  fullName: VRBuilder.Core.RestrictiveEnvironment.DefaultStepLockHandling
- uid: VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
  parent: VRBuilder.Core.RestrictiveEnvironment
  href: VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData.html
  name: LockablePropertyData
  nameWithType: LockablePropertyData
  fullName: VRBuilder.Core.RestrictiveEnvironment.LockablePropertyData
- uid: VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
  parent: VRBuilder.Core.RestrictiveEnvironment
  href: VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy.html
  name: StepLockHandlingStrategy
  nameWithType: StepLockHandlingStrategy
  fullName: VRBuilder.Core.RestrictiveEnvironment.StepLockHandlingStrategy
- uid: VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
  commentId: T:VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
  href: VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling.html
  name: NonLockingStepHandling
  nameWithType: NonLockingStepHandling
  fullName: VRBuilder.Core.RestrictiveEnvironment.NonLockingStepHandling
- uid: VRBuilder.Core.RestrictiveEnvironment
  commentId: N:VRBuilder.Core.RestrictiveEnvironment
  href: VRBuilder.html
  name: VRBuilder.Core.RestrictiveEnvironment
  nameWithType: VRBuilder.Core.RestrictiveEnvironment
  fullName: VRBuilder.Core.RestrictiveEnvironment
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.RestrictiveEnvironment
    name: RestrictiveEnvironment
    href: VRBuilder.Core.RestrictiveEnvironment.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.RestrictiveEnvironment
    name: RestrictiveEnvironment
    href: VRBuilder.Core.RestrictiveEnvironment.html
