### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  commentId: T:VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  id: IInteractionComponentConfiguration
  parent: VRBuilder.Core.Configuration
  children:
  - VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab
  - VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName
  - VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent
  langs:
  - csharp
  - vb
  name: IInteractionComponentConfiguration
  nameWithType: IInteractionComponentConfiguration
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  type: Interface
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IInteractionComponentConfiguration
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
    startLine: 5
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Should be implemented by every interaction component in order to qualify as such.
  example: []
  syntax:
    content: public interface IInteractionComponentConfiguration
    content.vb: Public Interface IInteractionComponentConfiguration
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName
  commentId: P:VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName
  id: DisplayName
  parent: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  langs:
  - csharp
  - vb
  name: DisplayName
  nameWithType: IInteractionComponentConfiguration.DisplayName
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: DisplayName
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
    startLine: 10
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Display name of the interaction component.
  example: []
  syntax:
    content: string DisplayName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property DisplayName As String
  overload: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName*
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent
  commentId: P:VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent
  id: IsXRInteractionComponent
  parent: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  langs:
  - csharp
  - vb
  name: IsXRInteractionComponent
  nameWithType: IInteractionComponentConfiguration.IsXRInteractionComponent
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: IsXRInteractionComponent
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
    startLine: 15
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: True if the interaction component is meant to work with XR.
  example: []
  syntax:
    content: bool IsXRInteractionComponent { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsXRInteractionComponent As Boolean
  overload: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent*
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab
  commentId: P:VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab
  id: DefaultRigPrefab
  parent: VRBuilder.Core.Configuration.IInteractionComponentConfiguration
  langs:
  - csharp
  - vb
  name: DefaultRigPrefab
  nameWithType: IInteractionComponentConfiguration.DefaultRigPrefab
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
      branch: release/v4.1.1
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: DefaultRigPrefab
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Configuration/IInteractionComponentConfiguration.cs
    startLine: 20
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Configuration
  summary: Name of the prefab to be spawned as user rig.
  example: []
  syntax:
    content: string DefaultRigPrefab { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property DefaultRigPrefab As String
  overload: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab*
references:
- uid: VRBuilder.Core.Configuration
  commentId: N:VRBuilder.Core.Configuration
  href: VRBuilder.html
  name: VRBuilder.Core.Configuration
  nameWithType: VRBuilder.Core.Configuration
  fullName: VRBuilder.Core.Configuration
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Configuration
    name: Configuration
    href: VRBuilder.Core.Configuration.html
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName*
  commentId: Overload:VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName
  href: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.html#VRBuilder_Core_Configuration_IInteractionComponentConfiguration_DisplayName
  name: DisplayName
  nameWithType: IInteractionComponentConfiguration.DisplayName
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DisplayName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent*
  commentId: Overload:VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent
  href: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.html#VRBuilder_Core_Configuration_IInteractionComponentConfiguration_IsXRInteractionComponent
  name: IsXRInteractionComponent
  nameWithType: IInteractionComponentConfiguration.IsXRInteractionComponent
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.IsXRInteractionComponent
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab*
  commentId: Overload:VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab
  href: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.html#VRBuilder_Core_Configuration_IInteractionComponentConfiguration_DefaultRigPrefab
  name: DefaultRigPrefab
  nameWithType: IInteractionComponentConfiguration.DefaultRigPrefab
  fullName: VRBuilder.Core.Configuration.IInteractionComponentConfiguration.DefaultRigPrefab
