### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag
  commentId: T:VRBuilder.Core.Settings.SceneObjectTags.Tag
  id: SceneObjectTags.Tag
  parent: VRBuilder.Core.Settings
  children:
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String)
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String,System.Guid)
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  langs:
  - csharp
  - vb
  name: SceneObjectTags.Tag
  nameWithType: SceneObjectTags.Tag
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag
  type: Class
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Tag
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 18
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: >-
      [Serializable]

      public class Tag
    content.vb: >-
      <Serializable>

      Public Class Tag
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  commentId: P:VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  id: Label
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Label
  nameWithType: SceneObjectTags.Tag.Label
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Label
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 27
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  summary: "\nText label for this tag.\n"
  example: []
  syntax:
    content: public string Label { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Label As String
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  commentId: P:VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  id: Guid
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Guid
  nameWithType: SceneObjectTags.Tag.Guid
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Guid
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 37
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  summary: "\nGuid representing the tag.\n"
  example: []
  syntax:
    content: public Guid Guid { get; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public ReadOnly Property Guid As Guid
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String)
  commentId: M:VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Tag(String)
  nameWithType: SceneObjectTags.Tag.Tag(String)
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Tag(System.String)
  type: Constructor
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 50
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public Tag(string label)
    parameters:
    - id: label
      type: System.String
    content.vb: Public Sub New(label As String)
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String,System.Guid)
  commentId: M:VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Tag(String, Guid)
  nameWithType: SceneObjectTags.Tag.Tag(String, Guid)
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Tag(System.String, System.Guid)
  type: Constructor
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 56
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public Tag(string label, Guid guid)
    parameters:
    - id: label
      type: System.String
    - id: guid
      type: System.Guid
    content.vb: Public Sub New(label As String, guid As Guid)
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  commentId: M:VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  id: Rename(System.String)
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Rename(String)
  nameWithType: SceneObjectTags.Tag.Rename(String)
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/mp-2811-outline-shader
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Rename
    path: ../../Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 62
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public void Rename(string label)
    parameters:
    - id: label
      type: System.String
    content.vb: Public Sub Rename(label As String)
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VRBuilder.Core.Settings
  commentId: N:VRBuilder.Core.Settings
  name: VRBuilder.Core.Settings
  nameWithType: VRBuilder.Core.Settings
  fullName: VRBuilder.Core.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  name: Label
  nameWithType: SceneObjectTags.Tag.Label
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  name: Guid
  nameWithType: SceneObjectTags.Tag.Guid
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor
  name: Tag
  nameWithType: SceneObjectTags.Tag.Tag
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Tag
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename
  name: Rename
  nameWithType: SceneObjectTags.Tag.Rename
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename
