### YamlMime:ManagedReference
items:
- uid: VRBuilder.Editor.Configuration.EditorConfigurator
  commentId: T:VRBuilder.Editor.Configuration.EditorConfigurator
  id: EditorConfigurator
  parent: VRBuilder.Editor.Configuration
  children:
  - VRBuilder.Editor.Configuration.EditorConfigurator.Init
  - VRBuilder.Editor.Configuration.EditorConfigurator.Instance
  langs:
  - csharp
  - vb
  name: EditorConfigurator
  nameWithType: EditorConfigurator
  fullName: VRBuilder.Editor.Configuration.EditorConfigurator
  type: Class
  source:
    remote:
      path: Source/Core/Editor/Configuration/EditorConfigurator.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: EditorConfigurator
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/EditorConfigurator.cs
    startLine: 20
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  summary: Configurator to set the process editor configuration which is used by the process creation editor tools (like Step Inspector).
  example: []
  syntax:
    content: public static class EditorConfigurator
    content.vb: Public Module EditorConfigurator
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: VRBuilder.Editor.Configuration.EditorConfigurator.Instance
  commentId: P:VRBuilder.Editor.Configuration.EditorConfigurator.Instance
  id: Instance
  parent: VRBuilder.Editor.Configuration.EditorConfigurator
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: EditorConfigurator.Instance
  fullName: VRBuilder.Editor.Configuration.EditorConfigurator.Instance
  type: Property
  source:
    remote:
      path: Source/Core/Editor/Configuration/EditorConfigurator.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Instance
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/EditorConfigurator.cs
    startLine: 24
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  syntax:
    content: public static DefaultEditorConfiguration Instance { get; }
    parameters: []
    return:
      type: VRBuilder.Editor.Configuration.DefaultEditorConfiguration
    content.vb: Public Shared ReadOnly Property Instance As DefaultEditorConfiguration
  overload: VRBuilder.Editor.Configuration.EditorConfigurator.Instance*
- uid: VRBuilder.Editor.Configuration.EditorConfigurator.Init
  commentId: M:VRBuilder.Editor.Configuration.EditorConfigurator.Init
  id: Init
  parent: VRBuilder.Editor.Configuration.EditorConfigurator
  langs:
  - csharp
  - vb
  name: Init()
  nameWithType: EditorConfigurator.Init()
  fullName: VRBuilder.Editor.Configuration.EditorConfigurator.Init()
  type: Method
  source:
    remote:
      path: Source/Core/Editor/Configuration/EditorConfigurator.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Init
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Editor/Configuration/EditorConfigurator.cs
    startLine: 34
  assemblies:
  - VRBuilder.Editor
  namespace: VRBuilder.Editor.Configuration
  syntax:
    content: public static void Init()
    content.vb: Public Shared Sub Init()
  overload: VRBuilder.Editor.Configuration.EditorConfigurator.Init*
references:
- uid: VRBuilder.Editor.Configuration
  commentId: N:VRBuilder.Editor.Configuration
  href: VRBuilder.html
  name: VRBuilder.Editor.Configuration
  nameWithType: VRBuilder.Editor.Configuration
  fullName: VRBuilder.Editor.Configuration
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Configuration
    name: Configuration
    href: VRBuilder.Editor.Configuration.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Editor
    name: Editor
    href: VRBuilder.Editor.html
  - name: .
  - uid: VRBuilder.Editor.Configuration
    name: Configuration
    href: VRBuilder.Editor.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Editor.Configuration.EditorConfigurator.Instance*
  commentId: Overload:VRBuilder.Editor.Configuration.EditorConfigurator.Instance
  href: VRBuilder.Editor.Configuration.EditorConfigurator.html#VRBuilder_Editor_Configuration_EditorConfigurator_Instance
  name: Instance
  nameWithType: EditorConfigurator.Instance
  fullName: VRBuilder.Editor.Configuration.EditorConfigurator.Instance
- uid: VRBuilder.Editor.Configuration.DefaultEditorConfiguration
  commentId: T:VRBuilder.Editor.Configuration.DefaultEditorConfiguration
  parent: VRBuilder.Editor.Configuration
  href: VRBuilder.Editor.Configuration.DefaultEditorConfiguration.html
  name: DefaultEditorConfiguration
  nameWithType: DefaultEditorConfiguration
  fullName: VRBuilder.Editor.Configuration.DefaultEditorConfiguration
- uid: VRBuilder.Editor.Configuration.EditorConfigurator.Init*
  commentId: Overload:VRBuilder.Editor.Configuration.EditorConfigurator.Init
  href: VRBuilder.Editor.Configuration.EditorConfigurator.html#VRBuilder_Editor_Configuration_EditorConfigurator_Init
  name: Init
  nameWithType: EditorConfigurator.Init
  fullName: VRBuilder.Editor.Configuration.EditorConfigurator.Init
