### YamlMime:ManagedReference
items:
- uid: VRBuilder.XRInteraction.Configuration
  commentId: N:VRBuilder.XRInteraction.Configuration
  id: VRBuilder.XRInteraction.Configuration
  children:
  - VRBuilder.XRInteraction.Configuration.XRInteractionComponentConfiguration
  langs:
  - csharp
  - vb
  name: VRBuilder.XRInteraction.Configuration
  nameWithType: VRBuilder.XRInteraction.Configuration
  fullName: VRBuilder.XRInteraction.Configuration
  type: Namespace
  assemblies:
  - VRBuilder.XRInteraction
references:
- uid: VRBuilder.XRInteraction.Configuration.XRInteractionComponentConfiguration
  commentId: T:VRBuilder.XRInteraction.Configuration.XRInteractionComponentConfiguration
  href: VRBuilder.XRInteraction.Configuration.XRInteractionComponentConfiguration.html
  name: XRInteractionComponentConfiguration
  nameWithType: XRInteractionComponentConfiguration
  fullName: VRBuilder.XRInteraction.Configuration.XRInteractionComponentConfiguration
