### YamlMime:ManagedReference
items:
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag
  commentId: T:VRBuilder.Core.Settings.SceneObjectTags.Tag
  id: SceneObjectTags.Tag
  parent: VRBuilder.Core.Settings
  children:
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String)
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String,System.Guid)
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  - VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  langs:
  - csharp
  - vb
  name: SceneObjectTags.Tag
  nameWithType: SceneObjectTags.Tag
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag
  type: Class
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Tag
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 18
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: >-
      [Serializable]

      public class SceneObjectTags.Tag
    content.vb: >-
      <Serializable>

      Public Class SceneObjectTags.Tag
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  commentId: P:VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  id: Label
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Label
  nameWithType: SceneObjectTags.Tag.Label
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Label
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 27
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  summary: Text label for this tag.
  example: []
  syntax:
    content: public string Label { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Label As String
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label*
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  commentId: P:VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  id: Guid
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Guid
  nameWithType: SceneObjectTags.Tag.Guid
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  type: Property
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Guid
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 37
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  summary: Guid representing the tag.
  example: []
  syntax:
    content: public Guid Guid { get; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public ReadOnly Property Guid As Guid
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid*
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String)
  commentId: M:VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Tag(string)
  nameWithType: SceneObjectTags.Tag.Tag(string)
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Tag(string)
  type: Constructor
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 50
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public Tag(string label)
    parameters:
    - id: label
      type: System.String
    content.vb: Public Sub New(label As String)
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor*
  nameWithType.vb: SceneObjectTags.Tag.New(String)
  fullName.vb: VRBuilder.Core.Settings.SceneObjectTags.Tag.New(String)
  name.vb: New(String)
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String,System.Guid)
  commentId: M:VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Tag(string, Guid)
  nameWithType: SceneObjectTags.Tag.Tag(string, Guid)
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Tag(string, System.Guid)
  type: Constructor
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: .ctor
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 56
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public Tag(string label, Guid guid)
    parameters:
    - id: label
      type: System.String
    - id: guid
      type: System.Guid
    content.vb: Public Sub New(label As String, guid As Guid)
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor*
  nameWithType.vb: SceneObjectTags.Tag.New(String, Guid)
  fullName.vb: VRBuilder.Core.Settings.SceneObjectTags.Tag.New(String, System.Guid)
  name.vb: New(String, Guid)
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  commentId: M:VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(System.String)
  id: Rename(System.String)
  parent: VRBuilder.Core.Settings.SceneObjectTags.Tag
  langs:
  - csharp
  - vb
  name: Rename(string)
  nameWithType: SceneObjectTags.Tag.Rename(string)
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(string)
  type: Method
  source:
    remote:
      path: Source/Core/Runtime/Settings/SceneObjectTags.cs
      branch: feature/docs
      repo: git@github.com:MindPort-GmbH/VR-Builder.git
    id: Rename
    path: ../../VR-Builder-UAS-2020/Assets/MindPort/VR Builder/Core/Source/Core/Runtime/Settings/SceneObjectTags.cs
    startLine: 62
  assemblies:
  - VRBuilder.Core
  namespace: VRBuilder.Core.Settings
  syntax:
    content: public void Rename(string label)
    parameters:
    - id: label
      type: System.String
    content.vb: Public Sub Rename(label As String)
  overload: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename*
  nameWithType.vb: SceneObjectTags.Tag.Rename(String)
  fullName.vb: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename(String)
  name.vb: Rename(String)
references:
- uid: VRBuilder.Core.Settings
  commentId: N:VRBuilder.Core.Settings
  href: VRBuilder.html
  name: VRBuilder.Core.Settings
  nameWithType: VRBuilder.Core.Settings
  fullName: VRBuilder.Core.Settings
  spec.csharp:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Settings
    name: Settings
    href: VRBuilder.Core.Settings.html
  spec.vb:
  - uid: VRBuilder
    name: VRBuilder
    href: VRBuilder.html
  - name: .
  - uid: VRBuilder.Core
    name: Core
    href: VRBuilder.Core.html
  - name: .
  - uid: VRBuilder.Core.Settings
    name: Settings
    href: VRBuilder.Core.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
  href: VRBuilder.Core.Settings.SceneObjectTags.Tag.html#VRBuilder_Core_Settings_SceneObjectTags_Tag_Label
  name: Label
  nameWithType: SceneObjectTags.Tag.Label
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Label
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
  href: VRBuilder.Core.Settings.SceneObjectTags.Tag.html#VRBuilder_Core_Settings_SceneObjectTags_Tag_Guid
  name: Guid
  nameWithType: SceneObjectTags.Tag.Guid
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Guid
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.#ctor
  href: VRBuilder.Core.Settings.SceneObjectTags.Tag.html#VRBuilder_Core_Settings_SceneObjectTags_Tag__ctor_System_String_
  name: Tag
  nameWithType: SceneObjectTags.Tag.Tag
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Tag
  nameWithType.vb: SceneObjectTags.Tag.New
  fullName.vb: VRBuilder.Core.Settings.SceneObjectTags.Tag.New
  name.vb: New
- uid: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename*
  commentId: Overload:VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename
  href: VRBuilder.Core.Settings.SceneObjectTags.Tag.html#VRBuilder_Core_Settings_SceneObjectTags_Tag_Rename_System_String_
  name: Rename
  nameWithType: SceneObjectTags.Tag.Rename
  fullName: VRBuilder.Core.Settings.SceneObjectTags.Tag.Rename
