apiRules:
- include: # The namespaces to generate
    uidRegex: VRBuilder.Core
    type: Namespace
- include:
    uidRegex: VRBuilder.Editor
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace
